import { defineConfig, mergeConfig } from 'vitest/config';
import viteConfig from './vite.config';

export default mergeConfig(viteConfig, defineConfig({
  test: {
    environment: 'jsdom',
    globals: true,
    setupFiles: ['./src/test/setup.ts'],
    css: true,
    coverage: {
      provider: 'v8',
      exclude: [
        'src/stores/adminStore.ts',
      ],
      include: [
        'src/stores/authStore.ts',
        'src/stores/gameStore.ts',
        'src/stores/playerStore.ts',
        'src/stores/drawingStore.ts',
        'src/stores/settingsStore.ts',
        'src/stores/friendStore.ts',
        'src/utils/cn.ts',
        'src/utils/avatars.ts',
        'src/utils/sounds.ts',
        'src/utils/authApi.ts',
        'src/utils/friendsApi.ts',
        'src/hooks/useGame.ts',
        'src/hooks/useUrlSync.ts',
        'src/hooks/useConfetti.ts',
        'src/hooks/useFriendEvents.ts',
        'src/components/Friends/**/*.tsx',
        'src/components/Auth/AuthModal.tsx',
        'src/components/UI/ConfirmModal.tsx',
        'src/components/UI/Pagination.tsx',
        'src/components/UI/CountrySelect.tsx',
        'src/components/UI/ConnectionStatus.tsx',
        'src/components/UI/PlayerLeftNotice.tsx',
        'src/components/Canvas/ToolBar.tsx',
        'src/components/Canvas/ColorPalette.tsx',
        'src/components/Game/Timer.tsx',
        'src/components/Game/WordDisplay.tsx',
        'src/components/Game/GameRoom.tsx',
        'src/components/Game/ReactionBar.tsx',
        'src/components/Game/FloatingReactions.tsx',
        'src/components/Lobby/CreateRoom.tsx',
        'src/components/Lobby/JoinRoom.tsx',
        'src/components/Lobby/AvailableRooms.tsx',
        'src/components/Lobby/OngoingGames.tsx',
        'src/components/Lobby/PublicLobbies.tsx',
        'src/components/Lobby/Leaderboard.tsx',
        'src/components/Lobby/PlayerList.tsx',
      ],
      thresholds: {
        branches: 70,
        functions: 80,
        lines: 80,
        statements: 80,
      },
    },
  },
}));
