/**
 * Bot-compatible words mapped to Google Quick Draw categories.
 * Each entry: [quickDrawCategory, { en, ka, ru, tr }, difficulty]
 *
 * Difficulty: 1=easy, 2=medium, 3=hard
 * All words here have botCompatible=true and a matching Quick Draw drawing.
 */

interface BotWordEntry {
  quickDraw: string;
  en: string;
  ka: string;
  ru: string;
  tr: string;
  difficulty: 1 | 2 | 3;
}

export const BOT_WORDS: BotWordEntry[] = [
  // ===== EASY (common, simple objects) =====
  // Animals - simple
  { quickDraw: 'cat', en: 'cat', ka: 'კატა', ru: 'кот', tr: 'kedi', difficulty: 1 },
  { quickDraw: 'dog', en: 'dog', ka: 'ძაღლი', ru: 'собака', tr: 'köpek', difficulty: 1 },
  { quickDraw: 'fish', en: 'fish', ka: 'თევზი', ru: 'рыба', tr: 'balık', difficulty: 1 },
  { quickDraw: 'bird', en: 'bird', ka: 'ფრინველი', ru: 'птица', tr: 'kuş', difficulty: 1 },
  { quickDraw: 'duck', en: 'duck', ka: 'იხვი', ru: 'утка', tr: 'ördek', difficulty: 1 },
  { quickDraw: 'pig', en: 'pig', ka: 'ღორი', ru: 'свинья', tr: 'domuz', difficulty: 1 },
  { quickDraw: 'cow', en: 'cow', ka: 'ძროხა', ru: 'корова', tr: 'inek', difficulty: 1 },
  { quickDraw: 'horse', en: 'horse', ka: 'ცხენი', ru: 'лошадь', tr: 'at', difficulty: 1 },
  { quickDraw: 'frog', en: 'frog', ka: 'ბაყაყი', ru: 'лягушка', tr: 'kurbağa', difficulty: 1 },
  { quickDraw: 'rabbit', en: 'rabbit', ka: 'კურდღელი', ru: 'кролик', tr: 'tavşan', difficulty: 1 },
  { quickDraw: 'bear', en: 'bear', ka: 'დათვი', ru: 'медведь', tr: 'ayı', difficulty: 1 },
  { quickDraw: 'snake', en: 'snake', ka: 'გველი', ru: 'змея', tr: 'yılan', difficulty: 1 },
  { quickDraw: 'spider', en: 'spider', ka: 'ობობა', ru: 'паук', tr: 'örümcek', difficulty: 1 },
  { quickDraw: 'butterfly', en: 'butterfly', ka: 'პეპელა', ru: 'бабочка', tr: 'kelebek', difficulty: 1 },
  { quickDraw: 'snail', en: 'snail', ka: 'ლოკოკინა', ru: 'улитка', tr: 'salyangoz', difficulty: 1 },
  { quickDraw: 'bee', en: 'bee', ka: 'ფუტკარი', ru: 'пчела', tr: 'arı', difficulty: 1 },
  { quickDraw: 'ant', en: 'ant', ka: 'ჭიანჭველა', ru: 'муравей', tr: 'karınca', difficulty: 1 },
  { quickDraw: 'monkey', en: 'monkey', ka: 'მაიმუნი', ru: 'обезьяна', tr: 'maymun', difficulty: 1 },
  { quickDraw: 'lion', en: 'lion', ka: 'ლომი', ru: 'лев', tr: 'aslan', difficulty: 1 },
  { quickDraw: 'elephant', en: 'elephant', ka: 'სპილო', ru: 'слон', tr: 'fil', difficulty: 1 },
  { quickDraw: 'penguin', en: 'penguin', ka: 'პინგვინი', ru: 'пингвин', tr: 'penguen', difficulty: 1 },
  { quickDraw: 'dolphin', en: 'dolphin', ka: 'დელფინი', ru: 'дельфин', tr: 'yunus', difficulty: 1 },
  { quickDraw: 'whale', en: 'whale', ka: 'ვეშაპი', ru: 'кит', tr: 'balina', difficulty: 1 },
  { quickDraw: 'shark', en: 'shark', ka: 'ზვიგენი', ru: 'акула', tr: 'köpekbalığı', difficulty: 1 },
  { quickDraw: 'turtle', en: 'turtle', ka: 'კუ', ru: 'черепаха', tr: 'kaplumbağa', difficulty: 1 },
  { quickDraw: 'crab', en: 'crab', ka: 'კიბორჩხალა', ru: 'краб', tr: 'yengeç', difficulty: 1 },
  { quickDraw: 'mouse', en: 'mouse', ka: 'თაგვი', ru: 'мышь', tr: 'fare', difficulty: 1 },
  { quickDraw: 'sheep', en: 'sheep', ka: 'ცხვარი', ru: 'овца', tr: 'koyun', difficulty: 1 },

  // Food - simple
  { quickDraw: 'apple', en: 'apple', ka: 'ვაშლი', ru: 'яблоко', tr: 'elma', difficulty: 1 },
  { quickDraw: 'banana', en: 'banana', ka: 'ბანანი', ru: 'банан', tr: 'muz', difficulty: 1 },
  { quickDraw: 'cake', en: 'cake', ka: 'ტორტი', ru: 'торт', tr: 'pasta', difficulty: 1 },
  { quickDraw: 'cookie', en: 'cookie', ka: 'ნამცხვარი', ru: 'печенье', tr: 'kurabiye', difficulty: 1 },
  { quickDraw: 'pizza', en: 'pizza', ka: 'პიცა', ru: 'пицца', tr: 'pizza', difficulty: 1 },
  { quickDraw: 'ice cream', en: 'ice cream', ka: 'ნაყინი', ru: 'мороженое', tr: 'dondurma', difficulty: 1 },
  { quickDraw: 'donut', en: 'donut', ka: 'დონატი', ru: 'пончик', tr: 'donut', difficulty: 1 },
  { quickDraw: 'hamburger', en: 'hamburger', ka: 'ჰამბურგერი', ru: 'гамбургер', tr: 'hamburger', difficulty: 1 },
  { quickDraw: 'hot dog', en: 'hot dog', ka: 'ჰოთდოგი', ru: 'хот-дог', tr: 'sosisli', difficulty: 1 },
  { quickDraw: 'bread', en: 'bread', ka: 'პური', ru: 'хлеб', tr: 'ekmek', difficulty: 1 },
  { quickDraw: 'egg', en: 'egg', ka: 'კვერცხი', ru: 'яйцо', tr: 'yumurta', difficulty: 1 },
  { quickDraw: 'carrot', en: 'carrot', ka: 'სტაფილო', ru: 'морковь', tr: 'havuç', difficulty: 1 },
  { quickDraw: 'grapes', en: 'grapes', ka: 'ყურძენი', ru: 'виноград', tr: 'üzüm', difficulty: 1 },
  { quickDraw: 'watermelon', en: 'watermelon', ka: 'საზამთრო', ru: 'арбуз', tr: 'karpuz', difficulty: 1 },
  { quickDraw: 'strawberry', en: 'strawberry', ka: 'მარწყვი', ru: 'клубника', tr: 'çilek', difficulty: 1 },
  { quickDraw: 'pear', en: 'pear', ka: 'მსხალი', ru: 'груша', tr: 'armut', difficulty: 1 },
  { quickDraw: 'mushroom', en: 'mushroom', ka: 'სოკო', ru: 'гриб', tr: 'mantar', difficulty: 1 },
  { quickDraw: 'onion', en: 'onion', ka: 'ხახვი', ru: 'лук', tr: 'soğan', difficulty: 1 },
  { quickDraw: 'lollipop', en: 'lollipop', ka: 'ლოლიპოპი', ru: 'леденец', tr: 'lolipop', difficulty: 1 },
  { quickDraw: 'popsicle', en: 'popsicle', ka: 'ესკიმო', ru: 'эскимо', tr: 'buzlu şeker', difficulty: 1 },
  { quickDraw: 'sandwich', en: 'sandwich', ka: 'სენდვიჩი', ru: 'сэндвич', tr: 'sandviç', difficulty: 1 },
  { quickDraw: 'pineapple', en: 'pineapple', ka: 'ანანასი', ru: 'ананас', tr: 'ananas', difficulty: 1 },
  { quickDraw: 'potato', en: 'potato', ka: 'კარტოფილი', ru: 'картошка', tr: 'patates', difficulty: 1 },

  // Common objects
  { quickDraw: 'star', en: 'star', ka: 'ვარსკვლავი', ru: 'звезда', tr: 'yıldız', difficulty: 1 },
  { quickDraw: 'moon', en: 'moon', ka: 'მთვარე', ru: 'луна', tr: 'ay', difficulty: 1 },
  { quickDraw: 'sun', en: 'sun', ka: 'მზე', ru: 'солнце', tr: 'güneş', difficulty: 1 },
  { quickDraw: 'cloud', en: 'cloud', ka: 'ღრუბელი', ru: 'облако', tr: 'bulut', difficulty: 1 },
  { quickDraw: 'rainbow', en: 'rainbow', ka: 'ცისარტყელა', ru: 'радуга', tr: 'gökkuşağı', difficulty: 1 },
  { quickDraw: 'rain', en: 'rain', ka: 'წვიმა', ru: 'дождь', tr: 'yağmur', difficulty: 1 },
  { quickDraw: 'snowflake', en: 'snowflake', ka: 'ფიფქი', ru: 'снежинка', tr: 'kar tanesi', difficulty: 1 },
  { quickDraw: 'snowman', en: 'snowman', ka: 'თოვლის კაცი', ru: 'снеговик', tr: 'kardan adam', difficulty: 1 },
  { quickDraw: 'tree', en: 'tree', ka: 'ხე', ru: 'дерево', tr: 'ağaç', difficulty: 1 },
  { quickDraw: 'flower', en: 'flower', ka: 'ყვავილი', ru: 'цветок', tr: 'çiçek', difficulty: 1 },
  { quickDraw: 'leaf', en: 'leaf', ka: 'ფოთოლი', ru: 'лист', tr: 'yaprak', difficulty: 1 },
  { quickDraw: 'grass', en: 'grass', ka: 'ბალახი', ru: 'трава', tr: 'çimen', difficulty: 1 },
  { quickDraw: 'house', en: 'house', ka: 'სახლი', ru: 'дом', tr: 'ev', difficulty: 1 },
  { quickDraw: 'door', en: 'door', ka: 'კარი', ru: 'дверь', tr: 'kapı', difficulty: 1 },
  { quickDraw: 'key', en: 'key', ka: 'გასაღები', ru: 'ключ', tr: 'anahtar', difficulty: 1 },
  { quickDraw: 'book', en: 'book', ka: 'წიგნი', ru: 'книга', tr: 'kitap', difficulty: 1 },
  { quickDraw: 'pencil', en: 'pencil', ka: 'ფანქარი', ru: 'карандаш', tr: 'kalem', difficulty: 1 },
  { quickDraw: 'scissors', en: 'scissors', ka: 'მაკრატელი', ru: 'ножницы', tr: 'makas', difficulty: 1 },
  { quickDraw: 'cup', en: 'cup', ka: 'ჭიქა', ru: 'чашка', tr: 'fincan', difficulty: 1 },
  { quickDraw: 'fork', en: 'fork', ka: 'ჩანგალი', ru: 'вилка', tr: 'çatal', difficulty: 1 },
  { quickDraw: 'spoon', en: 'spoon', ka: 'კოვზი', ru: 'ложка', tr: 'kaşık', difficulty: 1 },
  { quickDraw: 'knife', en: 'knife', ka: 'დანა', ru: 'нож', tr: 'bıçak', difficulty: 1 },
  { quickDraw: 'candle', en: 'candle', ka: 'სანთელი', ru: 'свеча', tr: 'mum', difficulty: 1 },
  { quickDraw: 'clock', en: 'clock', ka: 'საათი', ru: 'часы', tr: 'saat', difficulty: 1 },
  { quickDraw: 'hat', en: 'hat', ka: 'ქუდი', ru: 'шляпа', tr: 'şapka', difficulty: 1 },
  { quickDraw: 'shoe', en: 'shoe', ka: 'ფეხსაცმელი', ru: 'ботинок', tr: 'ayakkabı', difficulty: 1 },
  { quickDraw: 'sock', en: 'sock', ka: 'წინდა', ru: 'носок', tr: 'çorap', difficulty: 1 },
  { quickDraw: 'pants', en: 'pants', ka: 'შარვალი', ru: 'штаны', tr: 'pantolon', difficulty: 1 },
  { quickDraw: 't-shirt', en: 'shirt', ka: 'მაისური', ru: 'футболка', tr: 'tişört', difficulty: 1 },
  { quickDraw: 'bed', en: 'bed', ka: 'საწოლი', ru: 'кровать', tr: 'yatak', difficulty: 1 },
  { quickDraw: 'chair', en: 'chair', ka: 'სკამი', ru: 'стул', tr: 'sandalye', difficulty: 1 },
  { quickDraw: 'table', en: 'table', ka: 'მაგიდა', ru: 'стол', tr: 'masa', difficulty: 1 },
  { quickDraw: 'car', en: 'car', ka: 'მანქანა', ru: 'машина', tr: 'araba', difficulty: 1 },
  { quickDraw: 'bus', en: 'bus', ka: 'ავტობუსი', ru: 'автобус', tr: 'otobüs', difficulty: 1 },
  { quickDraw: 'bicycle', en: 'bicycle', ka: 'ველოსიპედი', ru: 'велосипед', tr: 'bisiklet', difficulty: 1 },
  { quickDraw: 'airplane', en: 'airplane', ka: 'თვითმფრინავი', ru: 'самолёт', tr: 'uçak', difficulty: 1 },
  { quickDraw: 'hammer', en: 'hammer', ka: 'ჩაქუჩი', ru: 'молоток', tr: 'çekiç', difficulty: 1 },
  { quickDraw: 'sword', en: 'sword', ka: 'ხმალი', ru: 'меч', tr: 'kılıç', difficulty: 1 },
  { quickDraw: 'crown', en: 'crown', ka: 'გვირგვინი', ru: 'корона', tr: 'taç', difficulty: 1 },
  { quickDraw: 'diamond', en: 'diamond', ka: 'ბრილიანტი', ru: 'бриллиант', tr: 'elmas', difficulty: 1 },
  { quickDraw: 'envelope', en: 'envelope', ka: 'კონვერტი', ru: 'конверт', tr: 'zarf', difficulty: 1 },
  { quickDraw: 'heart', en: 'heart', ka: 'გული', ru: 'сердце', tr: 'kalp', difficulty: 1 },
  { quickDraw: 'smiley face', en: 'smiley face', ka: 'ღიმილი', ru: 'смайлик', tr: 'gülen yüz', difficulty: 1 },
  { quickDraw: 'skull', en: 'skull', ka: 'თავის ქალა', ru: 'череп', tr: 'kafatası', difficulty: 1 },

  // ===== MEDIUM (less common objects, compound words) =====
  // Animals - medium
  { quickDraw: 'octopus', en: 'octopus', ka: 'რვაფეხა', ru: 'осьминог', tr: 'ahtapot', difficulty: 2 },
  { quickDraw: 'flamingo', en: 'flamingo', ka: 'ფლამინგო', ru: 'фламинго', tr: 'flamingo', difficulty: 2 },
  { quickDraw: 'giraffe', en: 'giraffe', ka: 'ჟირაფი', ru: 'жираф', tr: 'zürafa', difficulty: 2 },
  { quickDraw: 'camel', en: 'camel', ka: 'აქლემი', ru: 'верблюд', tr: 'deve', difficulty: 2 },
  { quickDraw: 'tiger', en: 'tiger', ka: 'ვეფხვი', ru: 'тигр', tr: 'kaplan', difficulty: 2 },
  { quickDraw: 'zebra', en: 'zebra', ka: 'ზებრა', ru: 'зебра', tr: 'zebra', difficulty: 2 },
  { quickDraw: 'kangaroo', en: 'kangaroo', ka: 'კენგურუ', ru: 'кенгуру', tr: 'kanguru', difficulty: 2 },
  { quickDraw: 'crocodile', en: 'crocodile', ka: 'ნიანგი', ru: 'крокодил', tr: 'timsah', difficulty: 2 },
  { quickDraw: 'lobster', en: 'lobster', ka: 'ლობსტერი', ru: 'лобстер', tr: 'ıstakoz', difficulty: 2 },
  { quickDraw: 'scorpion', en: 'scorpion', ka: 'მორიელი', ru: 'скорпион', tr: 'akrep', difficulty: 2 },
  { quickDraw: 'hedgehog', en: 'hedgehog', ka: 'ზღარბი', ru: 'ёж', tr: 'kirpi', difficulty: 2 },
  { quickDraw: 'owl', en: 'owl', ka: 'ბუ', ru: 'сова', tr: 'baykuş', difficulty: 2 },
  { quickDraw: 'panda', en: 'panda', ka: 'პანდა', ru: 'панда', tr: 'panda', difficulty: 2 },
  { quickDraw: 'rhinoceros', en: 'rhinoceros', ka: 'მარტორქა', ru: 'носорог', tr: 'gergedan', difficulty: 2 },
  { quickDraw: 'parrot', en: 'parrot', ka: 'თუთიყუში', ru: 'попугай', tr: 'papağan', difficulty: 2 },
  { quickDraw: 'squirrel', en: 'squirrel', ka: 'ციყვი', ru: 'белка', tr: 'sincap', difficulty: 2 },
  { quickDraw: 'raccoon', en: 'raccoon', ka: 'ენოტი', ru: 'енот', tr: 'rakun', difficulty: 2 },
  { quickDraw: 'swan', en: 'swan', ka: 'გედი', ru: 'лебедь', tr: 'kuğu', difficulty: 2 },
  { quickDraw: 'dragon', en: 'dragon', ka: 'დრაკონი', ru: 'дракон', tr: 'ejderha', difficulty: 2 },
  { quickDraw: 'bat', en: 'bat', ka: 'ღამურა', ru: 'летучая мышь', tr: 'yarasa', difficulty: 2 },
  { quickDraw: 'sea turtle', en: 'sea turtle', ka: 'ზღვის კუ', ru: 'морская черепаха', tr: 'deniz kaplumbağası', difficulty: 2 },
  { quickDraw: 'mosquito', en: 'mosquito', ka: 'კოღო', ru: 'комар', tr: 'sivrisinek', difficulty: 2 },

  // Vehicles & transport - medium
  { quickDraw: 'helicopter', en: 'helicopter', ka: 'ვერტმფრენი', ru: 'вертолёт', tr: 'helikopter', difficulty: 2 },
  { quickDraw: 'submarine', en: 'submarine', ka: 'წყალქვეშა', ru: 'подводная лодка', tr: 'denizaltı', difficulty: 2 },
  { quickDraw: 'sailboat', en: 'sailboat', ka: 'იალქანი', ru: 'парусник', tr: 'yelkenli', difficulty: 2 },
  { quickDraw: 'train', en: 'train', ka: 'მატარებელი', ru: 'поезд', tr: 'tren', difficulty: 2 },
  { quickDraw: 'truck', en: 'truck', ka: 'სატვირთო', ru: 'грузовик', tr: 'kamyon', difficulty: 2 },
  { quickDraw: 'ambulance', en: 'ambulance', ka: 'სასწრაფო', ru: 'скорая помощь', tr: 'ambulans', difficulty: 2 },
  { quickDraw: 'firetruck', en: 'fire truck', ka: 'სახანძრო', ru: 'пожарная машина', tr: 'itfaiye', difficulty: 2 },
  { quickDraw: 'motorbike', en: 'motorcycle', ka: 'მოტოციკლი', ru: 'мотоцикл', tr: 'motosiklet', difficulty: 2 },
  { quickDraw: 'tractor', en: 'tractor', ka: 'ტრაქტორი', ru: 'трактор', tr: 'traktör', difficulty: 2 },
  { quickDraw: 'canoe', en: 'canoe', ka: 'კანოე', ru: 'каноэ', tr: 'kano', difficulty: 2 },
  { quickDraw: 'pickup truck', en: 'pickup truck', ka: 'პიკაპი', ru: 'пикап', tr: 'pikap', difficulty: 2 },
  { quickDraw: 'police car', en: 'police car', ka: 'პოლიციის მანქანა', ru: 'полицейская машина', tr: 'polis arabası', difficulty: 2 },
  { quickDraw: 'school bus', en: 'school bus', ka: 'სასკოლო ავტობუსი', ru: 'школьный автобус', tr: 'okul otobüsü', difficulty: 2 },
  { quickDraw: 'speedboat', en: 'speedboat', ka: 'კატერი', ru: 'катер', tr: 'sürat teknesi', difficulty: 2 },
  { quickDraw: 'van', en: 'van', ka: 'მიკროავტობუსი', ru: 'фургон', tr: 'minivan', difficulty: 2 },
  { quickDraw: 'hot air balloon', en: 'hot air balloon', ka: 'საჰაერო ბუშტი', ru: 'воздушный шар', tr: 'sıcak hava balonu', difficulty: 2 },
  { quickDraw: 'roller coaster', en: 'roller coaster', ka: 'ამერიკული მთები', ru: 'американские горки', tr: 'hız treni', difficulty: 2 },

  // Buildings & structures
  { quickDraw: 'castle', en: 'castle', ka: 'ციხესიმაგრე', ru: 'замок', tr: 'kale', difficulty: 2 },
  { quickDraw: 'church', en: 'church', ka: 'ეკლესია', ru: 'церковь', tr: 'kilise', difficulty: 2 },
  { quickDraw: 'hospital', en: 'hospital', ka: 'საავადმყოფო', ru: 'больница', tr: 'hastane', difficulty: 2 },
  { quickDraw: 'lighthouse', en: 'lighthouse', ka: 'შუქურა', ru: 'маяк', tr: 'deniz feneri', difficulty: 2 },
  { quickDraw: 'bridge', en: 'bridge', ka: 'ხიდი', ru: 'мост', tr: 'köprü', difficulty: 2 },
  { quickDraw: 'tent', en: 'tent', ka: 'კარავი', ru: 'палатка', tr: 'çadır', difficulty: 2 },
  { quickDraw: 'fence', en: 'fence', ka: 'ღობე', ru: 'забор', tr: 'çit', difficulty: 2 },
  { quickDraw: 'barn', en: 'barn', ka: 'ბეღელი', ru: 'амбар', tr: 'ahır', difficulty: 2 },
  { quickDraw: 'windmill', en: 'windmill', ka: 'ქარის წისქვილი', ru: 'ветряная мельница', tr: 'yel değirmeni', difficulty: 2 },
  { quickDraw: 'skyscraper', en: 'skyscraper', ka: 'ცათამბჯენი', ru: 'небоскрёб', tr: 'gökdelen', difficulty: 2 },
  { quickDraw: 'stairs', en: 'stairs', ka: 'კიბე', ru: 'лестница', tr: 'merdiven', difficulty: 2 },
  { quickDraw: 'fireplace', en: 'fireplace', ka: 'ბუხარი', ru: 'камин', tr: 'şömine', difficulty: 2 },

  // Objects - medium
  { quickDraw: 'guitar', en: 'guitar', ka: 'გიტარა', ru: 'гитара', tr: 'gitar', difficulty: 2 },
  { quickDraw: 'piano', en: 'piano', ka: 'პიანინო', ru: 'пианино', tr: 'piyano', difficulty: 2 },
  { quickDraw: 'drums', en: 'drums', ka: 'დოლი', ru: 'барабан', tr: 'davul', difficulty: 2 },
  { quickDraw: 'violin', en: 'violin', ka: 'ვიოლინო', ru: 'скрипка', tr: 'keman', difficulty: 2 },
  { quickDraw: 'trumpet', en: 'trumpet', ka: 'საყვირი', ru: 'труба', tr: 'trompet', difficulty: 2 },
  { quickDraw: 'camera', en: 'camera', ka: 'კამერა', ru: 'фотоаппарат', tr: 'kamera', difficulty: 2 },
  { quickDraw: 'telephone', en: 'telephone', ka: 'ტელეფონი', ru: 'телефон', tr: 'telefon', difficulty: 2 },
  { quickDraw: 'television', en: 'television', ka: 'ტელევიზორი', ru: 'телевизор', tr: 'televizyon', difficulty: 2 },
  { quickDraw: 'laptop', en: 'laptop', ka: 'ლეპტოპი', ru: 'ноутбук', tr: 'dizüstü bilgisayar', difficulty: 2 },
  { quickDraw: 'umbrella', en: 'umbrella', ka: 'ქოლგა', ru: 'зонт', tr: 'şemsiye', difficulty: 2 },
  { quickDraw: 'backpack', en: 'backpack', ka: 'ზურგჩანთა', ru: 'рюкзак', tr: 'sırt çantası', difficulty: 2 },
  { quickDraw: 'suitcase', en: 'suitcase', ka: 'ჩემოდანი', ru: 'чемодан', tr: 'bavul', difficulty: 2 },
  { quickDraw: 'ladder', en: 'ladder', ka: 'კიბე', ru: 'стремянка', tr: 'merdiven', difficulty: 2 },
  { quickDraw: 'bucket', en: 'bucket', ka: 'ვედრო', ru: 'ведро', tr: 'kova', difficulty: 2 },
  { quickDraw: 'broom', en: 'broom', ka: 'ცოცხი', ru: 'метла', tr: 'süpürge', difficulty: 2 },
  { quickDraw: 'pillow', en: 'pillow', ka: 'ბალიში', ru: 'подушка', tr: 'yastık', difficulty: 2 },
  { quickDraw: 'couch', en: 'couch', ka: 'დივანი', ru: 'диван', tr: 'kanepe', difficulty: 2 },
  { quickDraw: 'floor lamp', en: 'lamp', ka: 'ლამპა', ru: 'лампа', tr: 'lamba', difficulty: 2 },
  { quickDraw: 'map', en: 'map', ka: 'რუკა', ru: 'карта', tr: 'harita', difficulty: 2 },
  { quickDraw: 'compass', en: 'compass', ka: 'კომპასი', ru: 'компас', tr: 'pusula', difficulty: 2 },
  { quickDraw: 'binoculars', en: 'binoculars', ka: 'ბინოკლი', ru: 'бинокль', tr: 'dürbün', difficulty: 2 },
  { quickDraw: 'hourglass', en: 'hourglass', ka: 'ქვიშის საათი', ru: 'песочные часы', tr: 'kum saati', difficulty: 2 },
  { quickDraw: 'anchor', en: 'anchor', ka: 'ღუზა', ru: 'якорь', tr: 'çapa', difficulty: 2 },
  { quickDraw: 'skateboard', en: 'skateboard', ka: 'სკეიტბორდი', ru: 'скейтборд', tr: 'kaykay', difficulty: 2 },
  { quickDraw: 'parachute', en: 'parachute', ka: 'პარაშუტი', ru: 'парашют', tr: 'paraşüt', difficulty: 2 },
  { quickDraw: 'boomerang', en: 'boomerang', ka: 'ბუმერანგი', ru: 'бумеранг', tr: 'bumerang', difficulty: 2 },
  { quickDraw: 'axe', en: 'axe', ka: 'ნაჯახი', ru: 'топор', tr: 'balta', difficulty: 2 },
  { quickDraw: 'saw', en: 'saw', ka: 'ხერხი', ru: 'пила', tr: 'testere', difficulty: 2 },
  { quickDraw: 'drill', en: 'drill', ka: 'ბურღი', ru: 'дрель', tr: 'matkap', difficulty: 2 },
  { quickDraw: 'nail', en: 'nail', ka: 'ლურსმანი', ru: 'гвоздь', tr: 'çivi', difficulty: 2 },
  { quickDraw: 'shovel', en: 'shovel', ka: 'ნიჩაბი', ru: 'лопата', tr: 'kürek', difficulty: 2 },
  { quickDraw: 'basket', en: 'basket', ka: 'კალათა', ru: 'корзина', tr: 'sepet', difficulty: 2 },
  { quickDraw: 'oven', en: 'oven', ka: 'ღუმელი', ru: 'духовка', tr: 'fırın', difficulty: 2 },
  { quickDraw: 'toilet', en: 'toilet', ka: 'ტუალეტი', ru: 'туалет', tr: 'tuvalet', difficulty: 2 },
  { quickDraw: 'bathtub', en: 'bathtub', ka: 'აბაზანა', ru: 'ванна', tr: 'küvet', difficulty: 2 },
  { quickDraw: 'sink', en: 'sink', ka: 'ნიჟარა', ru: 'раковина', tr: 'lavabo', difficulty: 2 },
  { quickDraw: 'trophy', en: 'trophy', ka: 'თასი', ru: 'кубок', tr: 'kupa', difficulty: 2 },
  { quickDraw: 'wristwatch', en: 'watch', ka: 'საათი', ru: 'наручные часы', tr: 'kol saati', difficulty: 2 },
  { quickDraw: 'eyeglasses', en: 'glasses', ka: 'სათვალე', ru: 'очки', tr: 'gözlük', difficulty: 2 },
  { quickDraw: 'helmet', en: 'helmet', ka: 'ჩაფხუტი', ru: 'шлем', tr: 'kask', difficulty: 2 },
  { quickDraw: 'necklace', en: 'necklace', ka: 'ყელსაბამი', ru: 'ожерелье', tr: 'kolye', difficulty: 2 },
  { quickDraw: 'sweater', en: 'sweater', ka: 'სვიტერი', ru: 'свитер', tr: 'kazak', difficulty: 2 },
  { quickDraw: 'jacket', en: 'jacket', ka: 'ქურთუკი', ru: 'куртка', tr: 'ceket', difficulty: 2 },
  { quickDraw: 'flip flops', en: 'flip flops', ka: 'ფლიპფლოპები', ru: 'шлёпанцы', tr: 'parmak arası terlik', difficulty: 2 },
  { quickDraw: 'kite', en: 'kite', ka: 'ფრანგი', ru: 'воздушный змей', tr: 'uçurtma', difficulty: 2 },
  { quickDraw: 'crayon', en: 'crayon', ka: 'ფანქარი', ru: 'мелок', tr: 'boya kalemi', difficulty: 2 },
  { quickDraw: 'paintbrush', en: 'paintbrush', ka: 'ფუნჯი', ru: 'кисть', tr: 'fırça', difficulty: 2 },
  { quickDraw: 'eraser', en: 'eraser', ka: 'საშლელი', ru: 'ластик', tr: 'silgi', difficulty: 2 },
  { quickDraw: 'calculator', en: 'calculator', ka: 'კალკულატორი', ru: 'калькулятор', tr: 'hesap makinesi', difficulty: 2 },
  { quickDraw: 'flashlight', en: 'flashlight', ka: 'ფანარი', ru: 'фонарик', tr: 'el feneri', difficulty: 2 },
  { quickDraw: 'lighter', en: 'lighter', ka: 'სანთებელა', ru: 'зажигалка', tr: 'çakmak', difficulty: 2 },
  { quickDraw: 'microphone', en: 'microphone', ka: 'მიკროფონი', ru: 'микрофон', tr: 'mikrofon', difficulty: 2 },
  { quickDraw: 'headphones', en: 'headphones', ka: 'ყურსასმენი', ru: 'наушники', tr: 'kulaklık', difficulty: 2 },
  { quickDraw: 'radio', en: 'radio', ka: 'რადიო', ru: 'радио', tr: 'radyo', difficulty: 2 },
  { quickDraw: 'remote control', en: 'remote control', ka: 'პულტი', ru: 'пульт', tr: 'uzaktan kumanda', difficulty: 2 },
  { quickDraw: 'keyboard', en: 'keyboard', ka: 'კლავიატურა', ru: 'клавиатура', tr: 'klavye', difficulty: 2 },
  { quickDraw: 'mug', en: 'mug', ka: 'კათხა', ru: 'кружка', tr: 'kupa', difficulty: 2 },
  { quickDraw: 'wine glass', en: 'wine glass', ka: 'ღვინის ჭიქა', ru: 'бокал', tr: 'kadeh', difficulty: 2 },
  { quickDraw: 'frying pan', en: 'frying pan', ka: 'ტაფა', ru: 'сковородка', tr: 'tava', difficulty: 2 },
  { quickDraw: 'teapot', en: 'teapot', ka: 'ჩაიდანი', ru: 'чайник', tr: 'çaydanlık', difficulty: 2 },
  { quickDraw: 'birthday cake', en: 'birthday cake', ka: 'დაბადების დღის ტორტი', ru: 'торт на день рождения', tr: 'doğum günü pastası', difficulty: 2 },
  { quickDraw: 'broccoli', en: 'broccoli', ka: 'ბროკოლი', ru: 'брокколи', tr: 'brokoli', difficulty: 2 },
  { quickDraw: 'steak', en: 'steak', ka: 'სტეიკი', ru: 'стейк', tr: 'biftek', difficulty: 2 },

  // Nature/landscape - medium
  { quickDraw: 'mountain', en: 'mountain', ka: 'მთა', ru: 'гора', tr: 'dağ', difficulty: 2 },
  { quickDraw: 'river', en: 'river', ka: 'მდინარე', ru: 'река', tr: 'nehir', difficulty: 2 },
  { quickDraw: 'ocean', en: 'ocean', ka: 'ოკეანე', ru: 'океан', tr: 'okyanus', difficulty: 2 },
  { quickDraw: 'beach', en: 'beach', ka: 'სანაპირო', ru: 'пляж', tr: 'plaj', difficulty: 2 },
  { quickDraw: 'cactus', en: 'cactus', ka: 'კაქტუსი', ru: 'кактус', tr: 'kaktüs', difficulty: 2 },
  { quickDraw: 'palm tree', en: 'palm tree', ka: 'პალმა', ru: 'пальма', tr: 'palmiye', difficulty: 2 },
  { quickDraw: 'tornado', en: 'tornado', ka: 'ტორნადო', ru: 'торнадо', tr: 'kasırga', difficulty: 2 },
  { quickDraw: 'hurricane', en: 'hurricane', ka: 'ქარიშხალი', ru: 'ураган', tr: 'fırtına', difficulty: 2 },
  { quickDraw: 'lightning', en: 'lightning', ka: 'ელვა', ru: 'молния', tr: 'şimşek', difficulty: 2 },
  { quickDraw: 'campfire', en: 'campfire', ka: 'კოცონი', ru: 'костёр', tr: 'kamp ateşi', difficulty: 2 },
  { quickDraw: 'pond', en: 'pond', ka: 'გუბე', ru: 'пруд', tr: 'gölet', difficulty: 2 },

  // Sports & misc - medium
  { quickDraw: 'soccer ball', en: 'soccer ball', ka: 'ფეხბურთის ბურთი', ru: 'футбольный мяч', tr: 'futbol topu', difficulty: 2 },
  { quickDraw: 'basketball', en: 'basketball', ka: 'კალათბურთი', ru: 'баскетбол', tr: 'basketbol', difficulty: 2 },
  { quickDraw: 'baseball bat', en: 'baseball bat', ka: 'ბეისბოლის ბატი', ru: 'бейсбольная бита', tr: 'beyzbol sopası', difficulty: 2 },
  { quickDraw: 'tennis racquet', en: 'tennis racket', ka: 'ჩოგბურთის ჩოგანი', ru: 'теннисная ракетка', tr: 'tenis raketi', difficulty: 2 },
  { quickDraw: 'dumbbell', en: 'dumbbell', ka: 'ჰანტელი', ru: 'гантель', tr: 'dambıl', difficulty: 2 },
  { quickDraw: 'surfboard', en: 'surfboard', ka: 'სერფის დაფა', ru: 'доска для серфинга', tr: 'sörf tahtası', difficulty: 2 },
  { quickDraw: 'rollerskates', en: 'roller skates', ka: 'როლიკები', ru: 'ролики', tr: 'paten', difficulty: 2 },
  { quickDraw: 'swing set', en: 'swing', ka: 'საქანელა', ru: 'качели', tr: 'salıncak', difficulty: 2 },
  { quickDraw: 'sled', en: 'sled', ka: 'საგორავი', ru: 'санки', tr: 'kızak', difficulty: 2 },
  { quickDraw: 'stop sign', en: 'stop sign', ka: 'გაჩერების ნიშანი', ru: 'знак стоп', tr: 'dur işareti', difficulty: 2 },
  { quickDraw: 'traffic light', en: 'traffic light', ka: 'შუქნიშანი', ru: 'светофор', tr: 'trafik lambası', difficulty: 2 },
  { quickDraw: 'fire hydrant', en: 'fire hydrant', ka: 'ჰიდრანტი', ru: 'пожарный гидрант', tr: 'yangın musluğu', difficulty: 2 },
  { quickDraw: 'mailbox', en: 'mailbox', ka: 'საფოსტო ყუთი', ru: 'почтовый ящик', tr: 'posta kutusu', difficulty: 2 },
  { quickDraw: 'streetlight', en: 'streetlight', ka: 'ფარანი', ru: 'фонарный столб', tr: 'sokak lambası', difficulty: 2 },
  { quickDraw: 'wheel', en: 'wheel', ka: 'ბორბალი', ru: 'колесо', tr: 'tekerlek', difficulty: 2 },
  { quickDraw: 'cannon', en: 'cannon', ka: 'ზარბაზანი', ru: 'пушка', tr: 'top', difficulty: 2 },
  { quickDraw: 'rifle', en: 'rifle', ka: 'თოფი', ru: 'ружьё', tr: 'tüfek', difficulty: 2 },
  { quickDraw: 'bandage', en: 'bandage', ka: 'ბინტი', ru: 'бинт', tr: 'bandaj', difficulty: 2 },
  { quickDraw: 'stethoscope', en: 'stethoscope', ka: 'სტეთოსკოპი', ru: 'стетоскоп', tr: 'stetoskop', difficulty: 2 },
  { quickDraw: 'syringe', en: 'syringe', ka: 'შპრიცი', ru: 'шприц', tr: 'şırınga', difficulty: 2 },
  { quickDraw: 'thermometer', en: 'thermometer', ka: 'თერმომეტრი', ru: 'градусник', tr: 'termometre', difficulty: 2 },
  { quickDraw: 'microscope', en: 'microscope', ka: 'მიკროსკოპი', ru: 'микроскоп', tr: 'mikroskop', difficulty: 2 },
  { quickDraw: 'light bulb', en: 'light bulb', ka: 'ნათურა', ru: 'лампочка', tr: 'ampul', difficulty: 2 },
  { quickDraw: 'power outlet', en: 'power outlet', ka: 'როზეტი', ru: 'розетка', tr: 'priz', difficulty: 2 },
  { quickDraw: 'washing machine', en: 'washing machine', ka: 'სარეცხი მანქანა', ru: 'стиральная машина', tr: 'çamaşır makinesi', difficulty: 2 },
  { quickDraw: 'microwave', en: 'microwave', ka: 'მიკროტალღური', ru: 'микроволновка', tr: 'mikrodalga', difficulty: 2 },
  { quickDraw: 'dishwasher', en: 'dishwasher', ka: 'ჭურჭლის სარეცხი', ru: 'посудомоечная машина', tr: 'bulaşık makinesi', difficulty: 2 },
  { quickDraw: 'dresser', en: 'dresser', ka: 'კომოდი', ru: 'комод', tr: 'şifonyer', difficulty: 2 },
  { quickDraw: 'ceiling fan', en: 'ceiling fan', ka: 'ვენტილატორი', ru: 'вентилятор', tr: 'tavan vantilatörü', difficulty: 2 },
  { quickDraw: 'picture frame', en: 'picture frame', ka: 'ჩარჩო', ru: 'рамка', tr: 'resim çerçevesi', difficulty: 2 },
  { quickDraw: 'vase', en: 'vase', ka: 'ვაზა', ru: 'ваза', tr: 'vazo', difficulty: 2 },
  { quickDraw: 'calendar', en: 'calendar', ka: 'კალენდარი', ru: 'календарь', tr: 'takvim', difficulty: 2 },
  { quickDraw: 'toothbrush', en: 'toothbrush', ka: 'კბილის ჯაგრისი', ru: 'зубная щётка', tr: 'diş fırçası', difficulty: 2 },
  { quickDraw: 'wine bottle', en: 'wine bottle', ka: 'ღვინის ბოთლი', ru: 'бутылка вина', tr: 'şarap şişesi', difficulty: 2 },
  { quickDraw: 'present', en: 'present', ka: 'საჩუქარი', ru: 'подарок', tr: 'hediye', difficulty: 2 },
  { quickDraw: 'teddy-bear', en: 'teddy bear', ka: 'დათუნია', ru: 'плюшевый мишка', tr: 'oyuncak ayı', difficulty: 2 },
  { quickDraw: 'cookie', en: 'cookie', ka: 'ნამცხვარი', ru: 'печенье', tr: 'kurabiye', difficulty: 2 },

  // ===== HARD (abstract, unusual, complex) =====
  { quickDraw: 'mermaid', en: 'mermaid', ka: 'ქალთევზა', ru: 'русалка', tr: 'deniz kızı', difficulty: 3 },
  { quickDraw: 'angel', en: 'angel', ka: 'ანგელოზი', ru: 'ангел', tr: 'melek', difficulty: 3 },
  { quickDraw: 'animal migration', en: 'animal migration', ka: 'ცხოველთა მიგრაცია', ru: 'миграция животных', tr: 'hayvan göçü', difficulty: 3 },
  { quickDraw: 'The Eiffel Tower', en: 'Eiffel Tower', ka: 'ეიფელის კოშკი', ru: 'Эйфелева башня', tr: 'Eyfel Kulesi', difficulty: 3 },
  { quickDraw: 'The Great Wall of China', en: 'Great Wall', ka: 'ჩინეთის კედელი', ru: 'Великая стена', tr: 'Çin Seddi', difficulty: 3 },
  { quickDraw: 'The Mona Lisa', en: 'Mona Lisa', ka: 'მონა ლიზა', ru: 'Мона Лиза', tr: 'Mona Lisa', difficulty: 3 },
  { quickDraw: 'flying saucer', en: 'UFO', ka: 'ამოუცნობი ობიექტი', ru: 'НЛО', tr: 'UFO', difficulty: 3 },
  { quickDraw: 'yoga', en: 'yoga', ka: 'იოგა', ru: 'йога', tr: 'yoga', difficulty: 3 },
  { quickDraw: 'snorkel', en: 'snorkel', ka: 'შნორკელი', ru: 'трубка для дайвинга', tr: 'şnorkel', difficulty: 3 },
  { quickDraw: 'diving board', en: 'diving board', ka: 'ტრამპლინი', ru: 'трамплин', tr: 'tramplen', difficulty: 3 },
  { quickDraw: 'sleeping bag', en: 'sleeping bag', ka: 'საძილე ტომარა', ru: 'спальный мешок', tr: 'uyku tulumu', difficulty: 3 },
  { quickDraw: 'cruise ship', en: 'cruise ship', ka: 'საკრუიზო გემი', ru: 'круизный лайнер', tr: 'yolcu gemisi', difficulty: 3 },
  { quickDraw: 'aircraft carrier', en: 'aircraft carrier', ka: 'ავიამზიდი', ru: 'авианосец', tr: 'uçak gemisi', difficulty: 3 },
  { quickDraw: 'bulldozer', en: 'bulldozer', ka: 'ბულდოზერი', ru: 'бульдозер', tr: 'buldozer', difficulty: 3 },
  { quickDraw: 'chandelier', en: 'chandelier', ka: 'ჭაღი', ru: 'люстра', tr: 'avize', difficulty: 3 },
  { quickDraw: 'anvil', en: 'anvil', ka: 'გრდემლი', ru: 'наковальня', tr: 'örs', difficulty: 3 },
  { quickDraw: 'accordion', en: 'accordion', ka: 'აკორდეონი', ru: 'аккордеон', tr: 'akordeon', difficulty: 3 },
  { quickDraw: 'cello', en: 'cello', ka: 'ჩელო', ru: 'виолончель', tr: 'çello', difficulty: 3 },
  { quickDraw: 'saxophone', en: 'saxophone', ka: 'საქსოფონი', ru: 'саксофон', tr: 'saksafon', difficulty: 3 },
  { quickDraw: 'trombone', en: 'trombone', ka: 'ტრომბონი', ru: 'тромбон', tr: 'trombon', difficulty: 3 },
  { quickDraw: 'harp', en: 'harp', ka: 'არფა', ru: 'арфа', tr: 'arp', difficulty: 3 },
  { quickDraw: 'clarinet', en: 'clarinet', ka: 'კლარნეტი', ru: 'кларнет', tr: 'klarnet', difficulty: 3 },
  { quickDraw: 'hockey stick', en: 'hockey stick', ka: 'ჰოკეის ჯოხი', ru: 'клюшка', tr: 'hokey sopası', difficulty: 3 },
  { quickDraw: 'hockey puck', en: 'hockey puck', ka: 'ჰოკეის შაიბა', ru: 'шайба', tr: 'hokey diski', difficulty: 3 },
  { quickDraw: 'golf club', en: 'golf club', ka: 'გოლფის ჯოხი', ru: 'клюшка для гольфа', tr: 'golf sopası', difficulty: 3 },
  { quickDraw: 'screwdriver', en: 'screwdriver', ka: 'ხრახნი', ru: 'отвёртка', tr: 'tornavida', difficulty: 3 },
  { quickDraw: 'pliers', en: 'pliers', ka: 'ტანგი', ru: 'плоскогубцы', tr: 'pense', difficulty: 3 },
  { quickDraw: 'paper clip', en: 'paper clip', ka: 'სამაგრი', ru: 'скрепка', tr: 'ataş', difficulty: 3 },
  { quickDraw: 'megaphone', en: 'megaphone', ka: 'მეგაფონი', ru: 'мегафон', tr: 'megafon', difficulty: 3 },
  { quickDraw: 'lantern', en: 'lantern', ka: 'ფარანი', ru: 'фонарь', tr: 'fener', difficulty: 3 },
  { quickDraw: 'compass', en: 'compass', ka: 'კომპასი', ru: 'компас', tr: 'pusula', difficulty: 3 },
  { quickDraw: 'toaster', en: 'toaster', ka: 'ტოსტერი', ru: 'тостер', tr: 'tost makinesi', difficulty: 3 },
  { quickDraw: 'stereo', en: 'stereo', ka: 'სტერეო', ru: 'магнитофон', tr: 'müzik seti', difficulty: 3 },
  { quickDraw: 'spreadsheet', en: 'spreadsheet', ka: 'ელცხრილი', ru: 'таблица', tr: 'elektronik tablo', difficulty: 3 },
  { quickDraw: 'passport', en: 'passport', ka: 'პასპორტი', ru: 'паспорт', tr: 'pasaport', difficulty: 3 },
  { quickDraw: 'postcard', en: 'postcard', ka: 'ღია ბარათი', ru: 'открытка', tr: 'kartpostal', difficulty: 3 },
  { quickDraw: 'purse', en: 'purse', ka: 'ჩანთა', ru: 'сумочка', tr: 'çanta', difficulty: 3 },
  { quickDraw: 'bowtie', en: 'bowtie', ka: 'პეპელა', ru: 'бабочка галстук', tr: 'papyon', difficulty: 3 },
  { quickDraw: 'bracelet', en: 'bracelet', ka: 'სამაჯური', ru: 'браслет', tr: 'bilezik', difficulty: 3 },
  { quickDraw: 'belt', en: 'belt', ka: 'ქამარი', ru: 'ремень', tr: 'kemer', difficulty: 3 },
  { quickDraw: 'bottlecap', en: 'bottle cap', ka: 'თავსახური', ru: 'крышка', tr: 'şişe kapağı', difficulty: 3 },
  { quickDraw: 'cooler', en: 'cooler', ka: 'მაცივარი', ru: 'кулер', tr: 'soğutucu', difficulty: 3 },
  { quickDraw: 'fan', en: 'fan', ka: 'ვენტილატორი', ru: 'вентилятор', tr: 'vantilatör', difficulty: 3 },
  { quickDraw: 'feather', en: 'feather', ka: 'ბუმბული', ru: 'перо', tr: 'tüy', difficulty: 3 },
  { quickDraw: 'garden hose', en: 'garden hose', ka: 'ბაღის შლანგი', ru: 'шланг', tr: 'bahçe hortumu', difficulty: 3 },
  { quickDraw: 'rake', en: 'rake', ka: 'გრაფა', ru: 'грабли', tr: 'tırmık', difficulty: 3 },
  { quickDraw: 'house plant', en: 'house plant', ka: 'ოთახის მცენარე', ru: 'комнатное растение', tr: 'ev bitkisi', difficulty: 3 },
  { quickDraw: 'stove', en: 'stove', ka: 'ქურა', ru: 'плита', tr: 'ocak', difficulty: 3 },
  { quickDraw: 'lipstick', en: 'lipstick', ka: 'პომადა', ru: 'помада', tr: 'ruj', difficulty: 3 },
  { quickDraw: 'marker', en: 'marker', ka: 'მარკერი', ru: 'маркер', tr: 'keçeli kalem', difficulty: 3 },
  { quickDraw: 'matches', en: 'matches', ka: 'ასანთი', ru: 'спички', tr: 'kibrit', difficulty: 3 },
  { quickDraw: 'paint can', en: 'paint can', ka: 'საღებავის ქილა', ru: 'банка краски', tr: 'boya kutusu', difficulty: 3 },
  { quickDraw: 'peanut', en: 'peanut', ka: 'არაქისი', ru: 'арахис', tr: 'fıstık', difficulty: 3 },
  { quickDraw: 'peas', en: 'peas', ka: 'ბარდა', ru: 'горох', tr: 'bezelye', difficulty: 3 },
  { quickDraw: 'hot tub', en: 'hot tub', ka: 'ჯაკუზი', ru: 'джакузи', tr: 'jakuzi', difficulty: 3 },
  { quickDraw: 'ice cream', en: 'ice cream cone', ka: 'ნაყინი', ru: 'рожок мороженого', tr: 'külah dondurma', difficulty: 3 },
  { quickDraw: 'waterslide', en: 'waterslide', ka: 'წყლის სრიალი', ru: 'водная горка', tr: 'su kaydırağı', difficulty: 3 },
  { quickDraw: 'see saw', en: 'see saw', ka: 'ჭანჭიკი', ru: 'качалка', tr: 'tahterevalli', difficulty: 3 },
  { quickDraw: 'slide', en: 'slide', ka: 'სრიალა', ru: 'горка', tr: 'kaydırak', difficulty: 3 },
  { quickDraw: 'stitches', en: 'stitches', ka: 'ნაკერი', ru: 'швы', tr: 'dikişler', difficulty: 3 },
  { quickDraw: 'tooth', en: 'tooth', ka: 'კბილი', ru: 'зуб', tr: 'diş', difficulty: 3 },
  { quickDraw: 'toothpaste', en: 'toothpaste', ka: 'კბილის პასტა', ru: 'зубная паста', tr: 'diş macunu', difficulty: 3 },
  { quickDraw: 'string bean', en: 'green bean', ka: 'ლობიო', ru: 'стручковая фасоль', tr: 'yeşil fasulye', difficulty: 3 },
  { quickDraw: 'broccoli', en: 'broccoli', ka: 'ბროკოლი', ru: 'брокколи', tr: 'brokoli', difficulty: 3 },
  { quickDraw: 'asparagus', en: 'asparagus', ka: 'სატაცურა', ru: 'спаржа', tr: 'kuşkonmaz', difficulty: 3 },
  { quickDraw: 'blackberry', en: 'blackberry', ka: 'მაყვალი', ru: 'ежевика', tr: 'böğürtlen', difficulty: 3 },
  { quickDraw: 'blueberry', en: 'blueberry', ka: 'მოცვი', ru: 'черника', tr: 'yaban mersini', difficulty: 3 },
  { quickDraw: 'pie', en: 'pie', ka: 'ღვეზელი', ru: 'пирог', tr: 'turta', difficulty: 3 },
  { quickDraw: 'baseball', en: 'baseball', ka: 'ბეისბოლი', ru: 'бейсбол', tr: 'beyzbol', difficulty: 3 },
  { quickDraw: 'camouflage', en: 'camouflage', ka: 'კამუფლაჟი', ru: 'камуфляж', tr: 'kamuflaj', difficulty: 3 },
  { quickDraw: 'cell phone', en: 'cell phone', ka: 'მობილური', ru: 'мобильный', tr: 'cep telefonu', difficulty: 3 },
  { quickDraw: 'computer', en: 'computer', ka: 'კომპიუტერი', ru: 'компьютер', tr: 'bilgisayar', difficulty: 3 },
  { quickDraw: 'dumbbell', en: 'dumbbell', ka: 'ჰანტელი', ru: 'гантель', tr: 'dambıl', difficulty: 3 },
  { quickDraw: 'goatee', en: 'goatee', ka: 'წვერი', ru: 'бородка', tr: 'keçi sakalı', difficulty: 3 },
  { quickDraw: 'moustache', en: 'mustache', ka: 'ულვაში', ru: 'усы', tr: 'bıyık', difficulty: 3 },
  { quickDraw: 'beard', en: 'beard', ka: 'წვერი', ru: 'борода', tr: 'sakal', difficulty: 3 },
  { quickDraw: 'face', en: 'face', ka: 'სახე', ru: 'лицо', tr: 'yüz', difficulty: 3 },
  { quickDraw: 'nose', en: 'nose', ka: 'ცხვირი', ru: 'нос', tr: 'burun', difficulty: 3 },
  { quickDraw: 'eye', en: 'eye', ka: 'თვალი', ru: 'глаз', tr: 'göz', difficulty: 3 },
  { quickDraw: 'ear', en: 'ear', ka: 'ყური', ru: 'ухо', tr: 'kulak', difficulty: 3 },
  { quickDraw: 'mouth', en: 'mouth', ka: 'პირი', ru: 'рот', tr: 'ağız', difficulty: 3 },
  { quickDraw: 'hand', en: 'hand', ka: 'ხელი', ru: 'рука', tr: 'el', difficulty: 3 },
  { quickDraw: 'foot', en: 'foot', ka: 'ფეხი', ru: 'нога', tr: 'ayak', difficulty: 3 },
  { quickDraw: 'arm', en: 'arm', ka: 'მკლავი', ru: 'рука', tr: 'kol', difficulty: 3 },
  { quickDraw: 'leg', en: 'leg', ka: 'ფეხი', ru: 'нога', tr: 'bacak', difficulty: 3 },
  { quickDraw: 'brain', en: 'brain', ka: 'ტვინი', ru: 'мозг', tr: 'beyin', difficulty: 3 },
  { quickDraw: 'finger', en: 'finger', ka: 'თითი', ru: 'палец', tr: 'parmak', difficulty: 3 },
  { quickDraw: 'knee', en: 'knee', ka: 'მუხლი', ru: 'колено', tr: 'diz', difficulty: 3 },
  { quickDraw: 'elbow', en: 'elbow', ka: 'იდაყვი', ru: 'локоть', tr: 'dirsek', difficulty: 3 },
  { quickDraw: 'toe', en: 'toe', ka: 'ფეხის თითი', ru: 'палец ноги', tr: 'ayak parmağı', difficulty: 3 },
  { quickDraw: 'zigzag', en: 'zigzag', ka: 'ზიგზაგი', ru: 'зигзаг', tr: 'zigzag', difficulty: 3 },
  { quickDraw: 'squiggle', en: 'squiggle', ka: 'ხაზი', ru: 'закорючка', tr: 'karalama', difficulty: 3 },
  { quickDraw: 'circle', en: 'circle', ka: 'წრე', ru: 'круг', tr: 'daire', difficulty: 3 },
  { quickDraw: 'square', en: 'square', ka: 'კვადრატი', ru: 'квадрат', tr: 'kare', difficulty: 3 },
  { quickDraw: 'triangle', en: 'triangle', ka: 'სამკუთხედი', ru: 'треугольник', tr: 'üçgen', difficulty: 3 },
  { quickDraw: 'hexagon', en: 'hexagon', ka: 'ექვსკუთხედი', ru: 'шестиугольник', tr: 'altıgen', difficulty: 3 },
  { quickDraw: 'octagon', en: 'octagon', ka: 'რვაკუთხედი', ru: 'восьмиугольник', tr: 'sekizgen', difficulty: 3 },
  { quickDraw: 'line', en: 'line', ka: 'ხაზი', ru: 'линия', tr: 'çizgi', difficulty: 3 },

  // ========== ADDITIONAL 300 WORDS ==========

  // ===== EASY — batch 2 (200 more easy words) =====
  // Animals - synonyms & related
  { quickDraw: 'dog', en: 'puppy', ka: 'ლეკვი', ru: 'щенок', tr: 'köpek yavrusu', difficulty: 1 },
  { quickDraw: 'cat', en: 'kitten', ka: 'კნუტი', ru: 'котёнок', tr: 'yavru kedi', difficulty: 1 },
  { quickDraw: 'horse', en: 'pony', ka: 'პონი', ru: 'пони', tr: 'midilli', difficulty: 1 },
  { quickDraw: 'bear', en: 'polar bear', ka: 'თეთრი დათვი', ru: 'белый медведь', tr: 'kutup ayısı', difficulty: 1 },
  { quickDraw: 'bird', en: 'sparrow', ka: 'ბეღურა', ru: 'воробей', tr: 'serçe', difficulty: 1 },
  { quickDraw: 'fish', en: 'goldfish', ka: 'ოქროს თევზი', ru: 'золотая рыбка', tr: 'japon balığı', difficulty: 1 },
  { quickDraw: 'duck', en: 'duckling', ka: 'იხვის ბარტყი', ru: 'утёнок', tr: 'ördek yavrusu', difficulty: 1 },
  { quickDraw: 'rabbit', en: 'bunny', ka: 'ბაჭია', ru: 'зайчик', tr: 'tavşancık', difficulty: 1 },
  { quickDraw: 'pig', en: 'piglet', ka: 'გოჭი', ru: 'поросёнок', tr: 'domuz yavrusu', difficulty: 1 },
  { quickDraw: 'cow', en: 'calf', ka: 'ხბო', ru: 'телёнок', tr: 'buzağı', difficulty: 1 },
  { quickDraw: 'sheep', en: 'lamb', ka: 'ბატკანი', ru: 'ягнёнок', tr: 'kuzu', difficulty: 1 },
  { quickDraw: 'lion', en: 'lion cub', ka: 'ლომის ბოკვერი', ru: 'львёнок', tr: 'aslan yavrusu', difficulty: 1 },
  { quickDraw: 'bird', en: 'robin', ka: 'წითელმკერდა', ru: 'малиновка', tr: 'kızılgerdan', difficulty: 1 },
  { quickDraw: 'ant', en: 'bug', ka: 'ბუზი', ru: 'жук', tr: 'böcek', difficulty: 1 },
  { quickDraw: 'spider', en: 'tarantula', ka: 'ტარანტულა', ru: 'тарантул', tr: 'tarantula', difficulty: 1 },
  { quickDraw: 'snail', en: 'slug', ka: 'შიშველი ლოკოკინა', ru: 'слизень', tr: 'sümüklü böcek', difficulty: 1 },
  { quickDraw: 'frog', en: 'toad', ka: 'გომბეშო', ru: 'жаба', tr: 'kara kurbağa', difficulty: 1 },
  { quickDraw: 'whale', en: 'blue whale', ka: 'ცისფერი ვეშაპი', ru: 'синий кит', tr: 'mavi balina', difficulty: 1 },
  { quickDraw: 'mouse', en: 'hamster', ka: 'ზაზუნა', ru: 'хомяк', tr: 'hamster', difficulty: 1 },
  { quickDraw: 'snake', en: 'cobra', ka: 'კობრა', ru: 'кобра', tr: 'kobra', difficulty: 1 },

  // Food & drinks - easy
  { quickDraw: 'cake', en: 'birthday cake', ka: 'დაბადების დღის ტორტი', ru: 'праздничный торт', tr: 'doğum günü pastası', difficulty: 1 },
  { quickDraw: 'pizza', en: 'pizza slice', ka: 'პიცის ნაჭერი', ru: 'кусок пиццы', tr: 'pizza dilimi', difficulty: 1 },
  { quickDraw: 'ice cream', en: 'ice cream cone', ka: 'ნაყინის კონუსი', ru: 'рожок мороженого', tr: 'dondurma külahı', difficulty: 1 },
  { quickDraw: 'cup', en: 'tea cup', ka: 'ჩაის ფინჯანი', ru: 'чайная чашка', tr: 'çay fincanı', difficulty: 1 },
  { quickDraw: 'mug', en: 'coffee mug', ka: 'ყავის ჭიქა', ru: 'кружка кофе', tr: 'kahve kupası', difficulty: 1 },
  { quickDraw: 'bread', en: 'toast', ka: 'ტოსტი', ru: 'тост', tr: 'tost', difficulty: 1 },
  { quickDraw: 'cookie', en: 'biscuit', ka: 'ორცხობილა', ru: 'бисквит', tr: 'bisküvi', difficulty: 1 },
  { quickDraw: 'hot dog', en: 'sausage', ka: 'სოსისი', ru: 'сосиска', tr: 'sosis', difficulty: 1 },
  { quickDraw: 'pie', en: 'pie', ka: 'ღვეზელი', ru: 'пирог', tr: 'turta', difficulty: 1 },
  { quickDraw: 'steak', en: 'steak', ka: 'სტეიკი', ru: 'стейк', tr: 'biftek', difficulty: 1 },
  { quickDraw: 'hamburger', en: 'cheeseburger', ka: 'ჩიზბურგერი', ru: 'чизбургер', tr: 'çizburger', difficulty: 1 },
  { quickDraw: 'grapes', en: 'cherry', ka: 'ბალი', ru: 'вишня', tr: 'kiraz', difficulty: 1 },
  { quickDraw: 'pear', en: 'peach', ka: 'ატამი', ru: 'персик', tr: 'şeftali', difficulty: 1 },
  { quickDraw: 'apple', en: 'green apple', ka: 'მწვანე ვაშლი', ru: 'зелёное яблоко', tr: 'yeşil elma', difficulty: 1 },
  { quickDraw: 'pineapple', en: 'mango', ka: 'მანგო', ru: 'манго', tr: 'mango', difficulty: 1 },
  { quickDraw: 'watermelon', en: 'melon', ka: 'ნესვი', ru: 'дыня', tr: 'kavun', difficulty: 1 },
  { quickDraw: 'strawberry', en: 'raspberry', ka: 'ჟოლო', ru: 'малина', tr: 'ahududu', difficulty: 1 },
  { quickDraw: 'broccoli', en: 'broccoli', ka: 'ბროკოლი', ru: 'брокколи', tr: 'brokoli', difficulty: 1 },
  { quickDraw: 'string bean', en: 'beans', ka: 'ლობიო', ru: 'фасоль', tr: 'fasulye', difficulty: 1 },
  { quickDraw: 'potato', en: 'french fries', ka: 'ფრი', ru: 'картофель фри', tr: 'patates kızartması', difficulty: 1 },

  // Household items - easy
  { quickDraw: 'television', en: 'TV', ka: 'ტელევიზორი', ru: 'телевизор', tr: 'televizyon', difficulty: 1 },
  { quickDraw: 'telephone', en: 'phone', ka: 'ტელეფონი', ru: 'телефон', tr: 'telefon', difficulty: 1 },
  { quickDraw: 'laptop', en: 'laptop', ka: 'ლეპტოპი', ru: 'ноутбук', tr: 'dizüstü bilgisayar', difficulty: 1 },
  { quickDraw: 'keyboard', en: 'keyboard', ka: 'კლავიატურა', ru: 'клавиатура', tr: 'klavye', difficulty: 1 },
  { quickDraw: 'computer', en: 'computer', ka: 'კომპიუტერი', ru: 'компьютер', tr: 'bilgisayar', difficulty: 1 },
  { quickDraw: 'camera', en: 'camera', ka: 'კამერა', ru: 'камера', tr: 'kamera', difficulty: 1 },
  { quickDraw: 'radio', en: 'radio', ka: 'რადიო', ru: 'радио', tr: 'radyo', difficulty: 1 },
  { quickDraw: 'headphones', en: 'headphones', ka: 'ყურსასმენი', ru: 'наушники', tr: 'kulaklık', difficulty: 1 },
  { quickDraw: 'microphone', en: 'microphone', ka: 'მიკროფონი', ru: 'микрофон', tr: 'mikrofon', difficulty: 1 },
  { quickDraw: 'flashlight', en: 'flashlight', ka: 'ფანარი', ru: 'фонарик', tr: 'el feneri', difficulty: 1 },
  { quickDraw: 'light bulb', en: 'light bulb', ka: 'ნათურა', ru: 'лампочка', tr: 'ampul', difficulty: 1 },
  { quickDraw: 'pillow', en: 'pillow', ka: 'ბალიში', ru: 'подушка', tr: 'yastık', difficulty: 1 },
  { quickDraw: 'bucket', en: 'bucket', ka: 'ვედრო', ru: 'ведро', tr: 'kova', difficulty: 1 },
  { quickDraw: 'broom', en: 'broom', ka: 'ცოცხი', ru: 'метла', tr: 'süpürge', difficulty: 1 },
  { quickDraw: 'ladder', en: 'ladder', ka: 'კიბე', ru: 'лестница', tr: 'merdiven', difficulty: 1 },
  { quickDraw: 'fence', en: 'fence', ka: 'ღობე', ru: 'забор', tr: 'çit', difficulty: 1 },
  { quickDraw: 'window', en: 'window', ka: 'ფანჯარა', ru: 'окно', tr: 'pencere', difficulty: 1 },
  { quickDraw: 'couch', en: 'sofa', ka: 'დივანი', ru: 'диван', tr: 'kanepe', difficulty: 1 },
  { quickDraw: 'bathtub', en: 'bathtub', ka: 'აბაზანა', ru: 'ванна', tr: 'küvet', difficulty: 1 },
  { quickDraw: 'toilet', en: 'toilet', ka: 'ტუალეტი', ru: 'туалет', tr: 'tuvalet', difficulty: 1 },

  // Nature & weather - easy
  { quickDraw: 'mountain', en: 'mountain', ka: 'მთა', ru: 'гора', tr: 'dağ', difficulty: 1 },
  { quickDraw: 'ocean', en: 'ocean', ka: 'ოკეანე', ru: 'океан', tr: 'okyanus', difficulty: 1 },
  { quickDraw: 'river', en: 'river', ka: 'მდინარე', ru: 'река', tr: 'nehir', difficulty: 1 },
  { quickDraw: 'lightning', en: 'lightning', ka: 'ელვა', ru: 'молния', tr: 'şimşek', difficulty: 1 },
  { quickDraw: 'tornado', en: 'tornado', ka: 'ტორნადო', ru: 'торнадо', tr: 'kasırga', difficulty: 1 },
  { quickDraw: 'cactus', en: 'cactus', ka: 'კაქტუსი', ru: 'кактус', tr: 'kaktüs', difficulty: 1 },
  { quickDraw: 'palm tree', en: 'palm tree', ka: 'პალმა', ru: 'пальма', tr: 'palmiye', difficulty: 1 },
  { quickDraw: 'pond', en: 'pond', ka: 'გუბე', ru: 'пруд', tr: 'gölet', difficulty: 1 },
  { quickDraw: 'beach', en: 'beach', ka: 'პლაჟი', ru: 'пляж', tr: 'plaj', difficulty: 1 },
  { quickDraw: 'campfire', en: 'campfire', ka: 'კოცონი', ru: 'костёр', tr: 'kamp ateşi', difficulty: 1 },

  // Clothing & accessories - easy
  { quickDraw: 'eyeglasses', en: 'glasses', ka: 'სათვალე', ru: 'очки', tr: 'gözlük', difficulty: 1 },
  { quickDraw: 'sweater', en: 'sweater', ka: 'სვიტერი', ru: 'свитер', tr: 'kazak', difficulty: 1 },
  { quickDraw: 'jacket', en: 'jacket', ka: 'ქურთუკი', ru: 'куртка', tr: 'ceket', difficulty: 1 },
  { quickDraw: 'belt', en: 'belt', ka: 'ქამარი', ru: 'ремень', tr: 'kemer', difficulty: 1 },
  { quickDraw: 'necklace', en: 'necklace', ka: 'ყელსაბამი', ru: 'ожерелье', tr: 'kolye', difficulty: 1 },
  { quickDraw: 'bracelet', en: 'bracelet', ka: 'სამაჯური', ru: 'браслет', tr: 'bilezik', difficulty: 1 },
  { quickDraw: 'backpack', en: 'backpack', ka: 'ზურგჩანთა', ru: 'рюкзак', tr: 'sırt çantası', difficulty: 1 },
  { quickDraw: 'purse', en: 'purse', ka: 'ჩანთა', ru: 'сумочка', tr: 'el çantası', difficulty: 1 },
  { quickDraw: 'suitcase', en: 'suitcase', ka: 'ჩემოდანი', ru: 'чемодан', tr: 'bavul', difficulty: 1 },
  { quickDraw: 'umbrella', en: 'umbrella', ka: 'ქოლგა', ru: 'зонт', tr: 'şemsiye', difficulty: 1 },

  // Tools & objects - easy
  { quickDraw: 'nail', en: 'nail', ka: 'ლურსმანი', ru: 'гвоздь', tr: 'çivi', difficulty: 1 },
  { quickDraw: 'saw', en: 'saw', ka: 'ხერხი', ru: 'пила', tr: 'testere', difficulty: 1 },
  { quickDraw: 'shovel', en: 'shovel', ka: 'ნიჩაბი', ru: 'лопата', tr: 'kürek', difficulty: 1 },
  { quickDraw: 'axe', en: 'axe', ka: 'ცული', ru: 'топор', tr: 'balta', difficulty: 1 },
  { quickDraw: 'screwdriver', en: 'screwdriver', ka: 'ხრახნიანი', ru: 'отвёртка', tr: 'tornavida', difficulty: 1 },
  { quickDraw: 'pliers', en: 'pliers', ka: 'ტანგა', ru: 'плоскогубцы', tr: 'pense', difficulty: 1 },
  { quickDraw: 'drill', en: 'drill', ka: 'ბურღი', ru: 'дрель', tr: 'matkap', difficulty: 1 },
  { quickDraw: 'paint can', en: 'paint can', ka: 'საღებავის ქილა', ru: 'банка краски', tr: 'boya kutusu', difficulty: 1 },
  { quickDraw: 'paintbrush', en: 'paintbrush', ka: 'ფუნჯი', ru: 'кисть', tr: 'boya fırçası', difficulty: 1 },
  { quickDraw: 'crayon', en: 'crayon', ka: 'ფერადი ფანქარი', ru: 'мелок', tr: 'pastel boya', difficulty: 1 },

  // Buildings & places - easy
  { quickDraw: 'castle', en: 'castle', ka: 'ციხე', ru: 'замок', tr: 'kale', difficulty: 1 },
  { quickDraw: 'church', en: 'church', ka: 'ეკლესია', ru: 'церковь', tr: 'kilise', difficulty: 1 },
  { quickDraw: 'hospital', en: 'hospital', ka: 'საავადმყოფო', ru: 'больница', tr: 'hastane', difficulty: 1 },
  { quickDraw: 'barn', en: 'barn', ka: 'ბეღელი', ru: 'амбар', tr: 'ahır', difficulty: 1 },
  { quickDraw: 'lighthouse', en: 'lighthouse', ka: 'შუქურა', ru: 'маяк', tr: 'deniz feneri', difficulty: 1 },
  { quickDraw: 'bridge', en: 'bridge', ka: 'ხიდი', ru: 'мост', tr: 'köprü', difficulty: 1 },
  { quickDraw: 'tent', en: 'tent', ka: 'კარავი', ru: 'палатка', tr: 'çadır', difficulty: 1 },
  { quickDraw: 'stairs', en: 'stairs', ka: 'კიბე', ru: 'ступеньки', tr: 'merdivenler', difficulty: 1 },
  { quickDraw: 'skyscraper', en: 'skyscraper', ka: 'ცათამბჯენი', ru: 'небоскрёб', tr: 'gökdelen', difficulty: 1 },
  { quickDraw: 'windmill', en: 'windmill', ka: 'ქარის წისქვილი', ru: 'мельница', tr: 'yel değirmeni', difficulty: 1 },

  // Sports & toys - easy
  { quickDraw: 'soccer ball', en: 'soccer ball', ka: 'ფეხბურთის ბურთი', ru: 'футбольный мяч', tr: 'futbol topu', difficulty: 1 },
  { quickDraw: 'basketball', en: 'basketball', ka: 'კალათბურთი', ru: 'баскетбольный мяч', tr: 'basketbol topu', difficulty: 1 },
  { quickDraw: 'baseball', en: 'baseball', ka: 'ბეისბოლი', ru: 'бейсбол', tr: 'beyzbol', difficulty: 1 },
  { quickDraw: 'baseball bat', en: 'baseball bat', ka: 'ბეისბოლის ბატი', ru: 'бейсбольная бита', tr: 'beyzbol sopası', difficulty: 1 },
  { quickDraw: 'tennis racquet', en: 'tennis racket', ka: 'ჩოგბურთის რაკეტი', ru: 'теннисная ракетка', tr: 'tenis raketi', difficulty: 1 },
  { quickDraw: 'skateboard', en: 'skateboard', ka: 'სკეიტბორდი', ru: 'скейтборд', tr: 'kaykay', difficulty: 1 },
  { quickDraw: 'kite', en: 'kite', ka: 'ფრანი', ru: 'воздушный змей', tr: 'uçurtma', difficulty: 1 },
  { quickDraw: 'helmet', en: 'helmet', ka: 'ჩაფხუტი', ru: 'шлем', tr: 'kask', difficulty: 1 },
  { quickDraw: 'trophy', en: 'trophy', ka: 'თასი', ru: 'трофей', tr: 'kupa', difficulty: 1 },
  { quickDraw: 'present', en: 'gift', ka: 'საჩუქარი', ru: 'подарок', tr: 'hediye', difficulty: 1 },

  // Vehicles - easy
  { quickDraw: 'van', en: 'van', ka: 'ფურგონი', ru: 'фургон', tr: 'minibüs', difficulty: 1 },
  { quickDraw: 'speedboat', en: 'speedboat', ka: 'ნავი', ru: 'катер', tr: 'sürat teknesi', difficulty: 1 },
  { quickDraw: 'sled', en: 'sled', ka: 'ციგა', ru: 'сани', tr: 'kızak', difficulty: 1 },
  { quickDraw: 'surfboard', en: 'surfboard', ka: 'სერფბორდი', ru: 'доска для сёрфинга', tr: 'sörf tahtası', difficulty: 1 },
  { quickDraw: 'hot air balloon', en: 'hot air balloon', ka: 'აეროსტატი', ru: 'воздушный шар', tr: 'sıcak hava balonu', difficulty: 1 },
  { quickDraw: 'cruise ship', en: 'cruise ship', ka: 'საკრუიზო გემი', ru: 'круизный корабль', tr: 'yolcu gemisi', difficulty: 1 },
  { quickDraw: 'rollerskates', en: 'roller skates', ka: 'როლიკები', ru: 'ролики', tr: 'paten', difficulty: 1 },
  { quickDraw: 'parachute', en: 'parachute', ka: 'პარაშუტი', ru: 'парашют', tr: 'paraşüt', difficulty: 1 },
  { quickDraw: 'bulldozer', en: 'bulldozer', ka: 'ბულდოზერი', ru: 'бульдозер', tr: 'buldozer', difficulty: 1 },
  { quickDraw: 'roller coaster', en: 'roller coaster', ka: 'ამერიკული გორკა', ru: 'американские горки', tr: 'lunapark treni', difficulty: 1 },

  // Music - easy
  { quickDraw: 'guitar', en: 'guitar', ka: 'გიტარა', ru: 'гитара', tr: 'gitar', difficulty: 1 },
  { quickDraw: 'piano', en: 'piano', ka: 'პიანინო', ru: 'пианино', tr: 'piyano', difficulty: 1 },
  { quickDraw: 'drums', en: 'drums', ka: 'დრამი', ru: 'барабан', tr: 'davul', difficulty: 1 },
  { quickDraw: 'trumpet', en: 'trumpet', ka: 'საყვირი', ru: 'труба', tr: 'trompet', difficulty: 1 },
  { quickDraw: 'violin', en: 'violin', ka: 'ვიოლინო', ru: 'скрипка', tr: 'keman', difficulty: 1 },
  { quickDraw: 'harp', en: 'harp', ka: 'არფა', ru: 'арфа', tr: 'arp', difficulty: 1 },

  // Kitchen & home - easy
  { quickDraw: 'oven', en: 'oven', ka: 'ღუმელი', ru: 'духовка', tr: 'fırın', difficulty: 1 },
  { quickDraw: 'frying pan', en: 'frying pan', ka: 'ტაფა', ru: 'сковорода', tr: 'tava', difficulty: 1 },
  { quickDraw: 'teapot', en: 'teapot', ka: 'ჩაიდანი', ru: 'чайник', tr: 'çaydanlık', difficulty: 1 },
  { quickDraw: 'sink', en: 'sink', ka: 'ნიჟარა', ru: 'раковина', tr: 'lavabo', difficulty: 1 },
  { quickDraw: 'vase', en: 'vase', ka: 'ვაზა', ru: 'ваза', tr: 'vazo', difficulty: 1 },
  { quickDraw: 'map', en: 'map', ka: 'რუკა', ru: 'карта', tr: 'harita', difficulty: 1 },
  { quickDraw: 'compass', en: 'compass', ka: 'კომპასი', ru: 'компас', tr: 'pusula', difficulty: 1 },
  { quickDraw: 'hourglass', en: 'hourglass', ka: 'ქვიშის საათი', ru: 'песочные часы', tr: 'kum saati', difficulty: 1 },
  { quickDraw: 'lantern', en: 'lantern', ka: 'ფანოსი', ru: 'фонарь', tr: 'fener', difficulty: 1 },
  { quickDraw: 'mailbox', en: 'mailbox', ka: 'საფოსტო ყუთი', ru: 'почтовый ящик', tr: 'posta kutusu', difficulty: 1 },

  // Body parts - easy
  { quickDraw: 'hand', en: 'hand', ka: 'ხელი', ru: 'ладонь', tr: 'el', difficulty: 1 },
  { quickDraw: 'eye', en: 'eye', ka: 'თვალი', ru: 'глаз', tr: 'göz', difficulty: 1 },
  { quickDraw: 'ear', en: 'ear', ka: 'ყური', ru: 'ухо', tr: 'kulak', difficulty: 1 },
  { quickDraw: 'nose', en: 'nose', ka: 'ცხვირი', ru: 'нос', tr: 'burun', difficulty: 1 },
  { quickDraw: 'mouth', en: 'mouth', ka: 'პირი', ru: 'рот', tr: 'ağız', difficulty: 1 },
  { quickDraw: 'face', en: 'face', ka: 'სახე', ru: 'лицо', tr: 'yüz', difficulty: 1 },
  { quickDraw: 'tooth', en: 'tooth', ka: 'კბილი', ru: 'зуб', tr: 'diş', difficulty: 1 },
  { quickDraw: 'foot', en: 'foot', ka: 'ტერფი', ru: 'ступня', tr: 'ayak', difficulty: 1 },

  // More household & everyday - easy
  { quickDraw: 'toothbrush', en: 'toothbrush', ka: 'კბილის ჯაგრისი', ru: 'зубная щётка', tr: 'diş fırçası', difficulty: 1 },
  { quickDraw: 'toothpaste', en: 'toothpaste', ka: 'კბილის პასტა', ru: 'зубная паста', tr: 'diş macunu', difficulty: 1 },
  { quickDraw: 'eraser', en: 'eraser', ka: 'საშლელი', ru: 'ластик', tr: 'silgi', difficulty: 1 },
  { quickDraw: 'marker', en: 'marker', ka: 'მარკერი', ru: 'маркер', tr: 'keçeli kalem', difficulty: 1 },
  { quickDraw: 'paper clip', en: 'paper clip', ka: 'ქაღალდის სამაგრი', ru: 'скрепка', tr: 'ataş', difficulty: 1 },
  { quickDraw: 'bandage', en: 'bandage', ka: 'ბინტი', ru: 'бинт', tr: 'bandaj', difficulty: 1 },
  { quickDraw: 'matches', en: 'matches', ka: 'ასანთი', ru: 'спички', tr: 'kibrit', difficulty: 1 },
  { quickDraw: 'rake', en: 'rake', ka: 'ფოცხი', ru: 'грабли', tr: 'tırmık', difficulty: 1 },

  // Miscellaneous easy
  { quickDraw: 'fire hydrant', en: 'fire hydrant', ka: 'ჰიდრანტი', ru: 'пожарный гидрант', tr: 'yangın musluğu', difficulty: 1 },
  { quickDraw: 'stop sign', en: 'stop sign', ka: 'გაჩერების ნიშანი', ru: 'знак стоп', tr: 'dur işareti', difficulty: 1 },
  { quickDraw: 'traffic light', en: 'traffic light', ka: 'შუქნიშანი', ru: 'светофор', tr: 'trafik lambası', difficulty: 1 },
  { quickDraw: 'anchor', en: 'anchor', ka: 'ღუზა', ru: 'якорь', tr: 'çapa', difficulty: 1 },
  { quickDraw: 'cannon', en: 'cannon', ka: 'ზარბაზანი', ru: 'пушка', tr: 'top', difficulty: 1 },
  { quickDraw: 'boomerang', en: 'boomerang', ka: 'ბუმერანგი', ru: 'бумеранг', tr: 'bumerang', difficulty: 1 },
  { quickDraw: 'flip flops', en: 'flip flops', ka: 'ჩუსტები', ru: 'шлёпанцы', tr: 'parmak arası terlik', difficulty: 1 },
  { quickDraw: 'sleeping bag', en: 'sleeping bag', ka: 'საძილე ტომარა', ru: 'спальный мешок', tr: 'uyku tulumu', difficulty: 1 },
  { quickDraw: 'picture frame', en: 'picture frame', ka: 'სურათის ჩარჩო', ru: 'рамка для фото', tr: 'resim çerçevesi', difficulty: 1 },
  { quickDraw: 'remote control', en: 'remote control', ka: 'პულტი', ru: 'пульт', tr: 'uzaktan kumanda', difficulty: 1 },
  { quickDraw: 'binoculars', en: 'binoculars', ka: 'ბინოკლი', ru: 'бинокль', tr: 'dürbün', difficulty: 1 },
  { quickDraw: 'basket', en: 'basket', ka: 'კალათი', ru: 'корзина', tr: 'sepet', difficulty: 1 },
  { quickDraw: 'wine bottle', en: 'bottle', ka: 'ბოთლი', ru: 'бутылка', tr: 'şişe', difficulty: 1 },
  { quickDraw: 'wine glass', en: 'wine glass', ka: 'ღვინის ჭიქა', ru: 'бокал', tr: 'kadeh', difficulty: 1 },
  { quickDraw: 'fan', en: 'fan', ka: 'ვენტილატორი', ru: 'вентилятор', tr: 'vantilatör', difficulty: 1 },
  { quickDraw: 'ceiling fan', en: 'ceiling fan', ka: 'ჭერის ვენტილატორი', ru: 'потолочный вентилятор', tr: 'tavan vantilatörü', difficulty: 1 },
  { quickDraw: 'dresser', en: 'dresser', ka: 'კომოდი', ru: 'комод', tr: 'şifonyer', difficulty: 1 },
  { quickDraw: 'teddy-bear', en: 'teddy bear', ka: 'დათვი სათამაშო', ru: 'плюшевый мишка', tr: 'oyuncak ayı', difficulty: 1 },

  // ===== MEDIUM — batch 2 (50 more medium words) =====
  { quickDraw: 'stethoscope', en: 'stethoscope', ka: 'სტეთოსკოპი', ru: 'стетоскоп', tr: 'stetoskop', difficulty: 2 },
  { quickDraw: 'microscope', en: 'microscope', ka: 'მიკროსკოპი', ru: 'микроскоп', tr: 'mikroskop', difficulty: 2 },
  { quickDraw: 'thermometer', en: 'thermometer', ka: 'თერმომეტრი', ru: 'термометр', tr: 'termometre', difficulty: 2 },
  { quickDraw: 'syringe', en: 'syringe', ka: 'შპრიცი', ru: 'шприц', tr: 'şırınga', difficulty: 2 },
  { quickDraw: 'chandelier', en: 'chandelier', ka: 'ჭაღი', ru: 'люстра', tr: 'avize', difficulty: 2 },
  { quickDraw: 'fireplace', en: 'fireplace', ka: 'ბუხარი', ru: 'камин', tr: 'şömine', difficulty: 2 },
  { quickDraw: 'washing machine', en: 'washing machine', ka: 'სარეცხი მანქანა', ru: 'стиральная машина', tr: 'çamaşır makinesi', difficulty: 2 },
  { quickDraw: 'dishwasher', en: 'dishwasher', ka: 'ჭურჭლის სარეცხი', ru: 'посудомоечная машина', tr: 'bulaşık makinesi', difficulty: 2 },
  { quickDraw: 'microwave', en: 'microwave', ka: 'მიკროტალღური', ru: 'микроволновка', tr: 'mikrodalga', difficulty: 2 },
  { quickDraw: 'toaster', en: 'toaster', ka: 'ტოსტერი', ru: 'тостер', tr: 'ekmek kızartma makinesi', difficulty: 2 },
  { quickDraw: 'calculator', en: 'calculator', ka: 'კალკულატორი', ru: 'калькулятор', tr: 'hesap makinesi', difficulty: 2 },
  { quickDraw: 'calendar', en: 'calendar', ka: 'კალენდარი', ru: 'календарь', tr: 'takvim', difficulty: 2 },
  { quickDraw: 'passport', en: 'passport', ka: 'პასპორტი', ru: 'паспорт', tr: 'pasaport', difficulty: 2 },
  { quickDraw: 'postcard', en: 'postcard', ka: 'ღია ბარათი', ru: 'открытка', tr: 'kartpostal', difficulty: 2 },
  { quickDraw: 'megaphone', en: 'megaphone', ka: 'მეგაფონი', ru: 'мегафон', tr: 'megafon', difficulty: 2 },
  { quickDraw: 'saxophone', en: 'saxophone', ka: 'საქსოფონი', ru: 'саксофон', tr: 'saksafon', difficulty: 2 },
  { quickDraw: 'cello', en: 'cello', ka: 'ჩელო', ru: 'виолончель', tr: 'çello', difficulty: 2 },
  { quickDraw: 'trombone', en: 'trombone', ka: 'ტრომბონი', ru: 'тромбон', tr: 'trombon', difficulty: 2 },
  { quickDraw: 'clarinet', en: 'clarinet', ka: 'კლარნეტი', ru: 'кларнет', tr: 'klarnet', difficulty: 2 },
  { quickDraw: 'accordion', en: 'accordion', ka: 'აკორდეონი', ru: 'аккордеон', tr: 'akordeon', difficulty: 2 },
  { quickDraw: 'golf club', en: 'golf club', ka: 'გოლფის ჯოხი', ru: 'клюшка для гольфа', tr: 'golf sopası', difficulty: 2 },
  { quickDraw: 'hockey stick', en: 'hockey stick', ka: 'ჰოკეის ჯოხი', ru: 'хоккейная клюшка', tr: 'hokey sopası', difficulty: 2 },
  { quickDraw: 'hockey puck', en: 'hockey puck', ka: 'შაიბა', ru: 'хоккейная шайба', tr: 'hokey diski', difficulty: 2 },
  { quickDraw: 'diving board', en: 'diving board', ka: 'ტრამპლინი', ru: 'трамплин', tr: 'tramplen', difficulty: 2 },
  { quickDraw: 'swing set', en: 'swing', ka: 'საქანელა', ru: 'качели', tr: 'salıncak', difficulty: 2 },
  { quickDraw: 'slide', en: 'slide', ka: 'სრიალი', ru: 'горка', tr: 'kaydırak', difficulty: 2 },
  { quickDraw: 'see saw', en: 'seesaw', ka: 'კაჭკაჭი', ru: 'качели-балансир', tr: 'tahterevalli', difficulty: 2 },
  { quickDraw: 'waterslide', en: 'waterslide', ka: 'წყლის სრიალი', ru: 'водная горка', tr: 'su kaydırağı', difficulty: 2 },
  { quickDraw: 'garden hose', en: 'garden hose', ka: 'ბაღის შლანგი', ru: 'садовый шланг', tr: 'bahçe hortumu', difficulty: 2 },
  { quickDraw: 'house plant', en: 'house plant', ka: 'ოთახის მცენარე', ru: 'комнатное растение', tr: 'ev bitkisi', difficulty: 2 },
  { quickDraw: 'birthday cake', en: 'birthday cake', ka: 'საიუბილეო ტორტი', ru: 'именинный торт', tr: 'yaş günü pastası', difficulty: 2 },
  { quickDraw: 'cooler', en: 'cooler', ka: 'გამაცივებელი', ru: 'холодильник', tr: 'soğutucu', difficulty: 2 },
  { quickDraw: 'power outlet', en: 'power outlet', ka: 'როზეტი', ru: 'розетка', tr: 'priz', difficulty: 2 },
  { quickDraw: 'stereo', en: 'stereo', ka: 'სტერეო', ru: 'стереосистема', tr: 'müzik seti', difficulty: 2 },
  { quickDraw: 'streetlight', en: 'streetlight', ka: 'ქუჩის ფანარი', ru: 'уличный фонарь', tr: 'sokak lambası', difficulty: 2 },
  { quickDraw: 'dumbbell', en: 'dumbbell', ka: 'ჰანტელი', ru: 'гантель', tr: 'dambıl', difficulty: 2 },
  { quickDraw: 'wristwatch', en: 'wristwatch', ka: 'მაჯის საათი', ru: 'наручные часы', tr: 'kol saati', difficulty: 2 },
  { quickDraw: 'cell phone', en: 'cell phone', ka: 'მობილური', ru: 'мобильник', tr: 'cep telefonu', difficulty: 2 },
  { quickDraw: 'lighter', en: 'lighter', ka: 'სანთებელა', ru: 'зажигалка', tr: 'çakmak', difficulty: 2 },
  { quickDraw: 'lipstick', en: 'lipstick', ka: 'პომადა', ru: 'помада', tr: 'ruj', difficulty: 2 },
  { quickDraw: 'feather', en: 'feather', ka: 'ბუმბული', ru: 'перо', tr: 'tüy', difficulty: 2 },
  { quickDraw: 'bowtie', en: 'bowtie', ka: 'პეპელა', ru: 'бабочка', tr: 'papyon', difficulty: 2 },
  { quickDraw: 'snorkel', en: 'snorkel', ka: 'სნორკელი', ru: 'трубка для плавания', tr: 'şnorkel', difficulty: 2 },
  { quickDraw: 'anvil', en: 'anvil', ka: 'გრდემლი', ru: 'наковальня', tr: 'örs', difficulty: 2 },
  { quickDraw: 'bottlecap', en: 'bottle cap', ka: 'ბოთლის თავსახური', ru: 'крышка от бутылки', tr: 'şişe kapağı', difficulty: 2 },
  { quickDraw: 'peanut', en: 'peanut', ka: 'არაქისი', ru: 'арахис', tr: 'fıstık', difficulty: 2 },
  { quickDraw: 'peas', en: 'peas', ka: 'ბარდა', ru: 'горох', tr: 'bezelye', difficulty: 2 },
  { quickDraw: 'asparagus', en: 'asparagus', ka: 'სატაცური', ru: 'спаржа', tr: 'kuşkonmaz', difficulty: 2 },
  { quickDraw: 'blackberry', en: 'blackberry', ka: 'მაყვალი', ru: 'ежевика', tr: 'böğürtlen', difficulty: 2 },
  { quickDraw: 'blueberry', en: 'blueberry', ka: 'მოცვი', ru: 'черника', tr: 'yaban mersini', difficulty: 2 },

  // ===== HARD — batch 2 (50 more hard words) =====
  { quickDraw: 'The Eiffel Tower', en: 'Eiffel Tower', ka: 'ეიფელის კოშკი', ru: 'Эйфелева башня', tr: 'Eyfel Kulesi', difficulty: 3 },
  { quickDraw: 'The Great Wall of China', en: 'Great Wall', ka: 'ჩინეთის კედელი', ru: 'Великая стена', tr: 'Çin Seddi', difficulty: 3 },
  { quickDraw: 'The Mona Lisa', en: 'Mona Lisa', ka: 'მონა ლიზა', ru: 'Мона Лиза', tr: 'Mona Lisa', difficulty: 3 },
  { quickDraw: 'mermaid', en: 'mermaid', ka: 'ქალთევზა', ru: 'русалка', tr: 'deniz kızı', difficulty: 3 },
  { quickDraw: 'angel', en: 'angel', ka: 'ანგელოზი', ru: 'ангел', tr: 'melek', difficulty: 3 },
  { quickDraw: 'yoga', en: 'yoga', ka: 'იოგა', ru: 'йога', tr: 'yoga', difficulty: 3 },
  { quickDraw: 'animal migration', en: 'animal migration', ka: 'ცხოველთა მიგრაცია', ru: 'миграция животных', tr: 'hayvan göçü', difficulty: 3 },
  { quickDraw: 'camouflage', en: 'camouflage', ka: 'კამუფლაჟი', ru: 'камуфляж', tr: 'kamuflaj', difficulty: 3 },
  { quickDraw: 'hurricane', en: 'hurricane', ka: 'ქარიშხალი', ru: 'ураган', tr: 'fırtına', difficulty: 3 },
  { quickDraw: 'flying saucer', en: 'flying saucer', ka: 'მფრინავი თეფში', ru: 'летающая тарелка', tr: 'uçan daire', difficulty: 3 },
  { quickDraw: 'hot tub', en: 'hot tub', ka: 'ჯაკუზი', ru: 'джакузи', tr: 'jakuzi', difficulty: 3 },
  { quickDraw: 'spreadsheet', en: 'spreadsheet', ka: 'ცხრილი', ru: 'таблица', tr: 'elektronik tablo', difficulty: 3 },
  { quickDraw: 'stitches', en: 'stitches', ka: 'ნაკერი', ru: 'швы', tr: 'dikişler', difficulty: 3 },
  { quickDraw: 'goatee', en: 'goatee', ka: 'წვერი', ru: 'бородка', tr: 'keçi sakalı', difficulty: 3 },
  { quickDraw: 'moustache', en: 'moustache', ka: 'ულვაში', ru: 'усы', tr: 'bıyık', difficulty: 3 },
  { quickDraw: 'beard', en: 'beard', ka: 'წვერი', ru: 'борода', tr: 'sakal', difficulty: 3 },
  { quickDraw: 'aircraft carrier', en: 'aircraft carrier', ka: 'ავიამზიდი', ru: 'авианосец', tr: 'uçak gemisi', difficulty: 3 },
  { quickDraw: 'rifle', en: 'rifle', ka: 'თოფი', ru: 'винтовка', tr: 'tüfek', difficulty: 3 },
  { quickDraw: 'stove', en: 'stove', ka: 'ღუმელი', ru: 'плита', tr: 'soba', difficulty: 3 },
  { quickDraw: 'floor lamp', en: 'floor lamp', ka: 'იატაკის ლამპა', ru: 'торшер', tr: 'ayaklı lamba', difficulty: 3 },
  { quickDraw: 'flag', en: 'flag', ka: 'დროშა', ru: 'флаг', tr: 'bayrak', difficulty: 3 },
  { quickDraw: 'whale', en: 'narwhal', ka: 'ნარვალი', ru: 'нарвал', tr: 'deniz gergedanı', difficulty: 3 },
  { quickDraw: 'shark', en: 'hammerhead', ka: 'ჩაქუჩთავა', ru: 'молот-рыба', tr: 'çekiç başlı köpekbalığı', difficulty: 3 },
  { quickDraw: 'bird', en: 'pelican', ka: 'ვარხვი', ru: 'пеликан', tr: 'pelikan', difficulty: 3 },
  { quickDraw: 'spider', en: 'black widow', ka: 'შავი ქვრივი', ru: 'чёрная вдова', tr: 'kara dul', difficulty: 3 },
  { quickDraw: 'crocodile', en: 'alligator', ka: 'ალიგატორი', ru: 'аллигатор', tr: 'timsah', difficulty: 3 },
  { quickDraw: 'bat', en: 'vampire bat', ka: 'ვამპირი ღამურა', ru: 'вампир', tr: 'vampir yarasa', difficulty: 3 },
  { quickDraw: 'octopus', en: 'squid', ka: 'კალმარი', ru: 'кальмар', tr: 'kalamar', difficulty: 3 },
  { quickDraw: 'lobster', en: 'shrimp', ka: 'კრევეტი', ru: 'креветка', tr: 'karides', difficulty: 3 },
  { quickDraw: 'snake', en: 'python', ka: 'პითონი', ru: 'питон', tr: 'piton', difficulty: 3 },
  { quickDraw: 'guitar', en: 'banjo', ka: 'ბანჯო', ru: 'банджо', tr: 'banjo', difficulty: 3 },
  { quickDraw: 'violin', en: 'fiddle', ka: 'ფიდელი', ru: 'скрипка', tr: 'keman', difficulty: 3 },
  { quickDraw: 'harp', en: 'lyre', ka: 'ლირა', ru: 'лира', tr: 'lir', difficulty: 3 },
  { quickDraw: 'castle', en: 'fortress', ka: 'ციხესიმაგრე', ru: 'крепость', tr: 'hisar', difficulty: 3 },
  { quickDraw: 'church', en: 'cathedral', ka: 'ტაძარი', ru: 'собор', tr: 'katedral', difficulty: 3 },
  { quickDraw: 'bridge', en: 'drawbridge', ka: 'აწეული ხიდი', ru: 'подъёмный мост', tr: 'asma köprü', difficulty: 3 },
  { quickDraw: 'telescope', en: 'telescope', ka: 'ტელესკოპი', ru: 'телескоп', tr: 'teleskop', difficulty: 3 },
  { quickDraw: 'submarine', en: 'bathysphere', ka: 'ბათისფერო', ru: 'батисфера', tr: 'batiskaf', difficulty: 3 },
  { quickDraw: 'helicopter', en: 'chopper', ka: 'ვერტმფრენი', ru: 'вертушка', tr: 'helikopter', difficulty: 3 },
  { quickDraw: 'airplane', en: 'biplane', ka: 'ბიპლანი', ru: 'биплан', tr: 'çift kanatlı uçak', difficulty: 3 },
  { quickDraw: 'sailboat', en: 'galleon', ka: 'გალეონი', ru: 'галеон', tr: 'kalyon', difficulty: 3 },
  { quickDraw: 'bus', en: 'double decker bus', ka: 'ორსართულიანი ავტობუსი', ru: 'двухэтажный автобус', tr: 'çift katlı otobüs', difficulty: 3 },
  { quickDraw: 'train', en: 'locomotive', ka: 'ლოკომოტივი', ru: 'локомотив', tr: 'lokomotif', difficulty: 3 },
  { quickDraw: 'car', en: 'limousine', ka: 'ლიმუზინი', ru: 'лимузин', tr: 'limuzin', difficulty: 3 },
  { quickDraw: 'bicycle', en: 'tandem bike', ka: 'ტანდემი', ru: 'тандем', tr: 'tandem bisiklet', difficulty: 3 },
  { quickDraw: 'tree', en: 'bonsai', ka: 'ბონსაი', ru: 'бонсай', tr: 'bonsai', difficulty: 3 },
  { quickDraw: 'flower', en: 'orchid', ka: 'ორქიდეა', ru: 'орхидея', tr: 'orkide', difficulty: 3 },
  { quickDraw: 'mushroom', en: 'toadstool', ka: 'მუხლუხო', ru: 'мухомор', tr: 'zehirli mantar', difficulty: 3 },
  { quickDraw: 'cactus', en: 'succulent', ka: 'სუკულენტი', ru: 'суккулент', tr: 'etli bitki', difficulty: 3 },
  { quickDraw: 'leaf', en: 'maple leaf', ka: 'ნეკერჩხლის ფოთოლი', ru: 'кленовый лист', tr: 'akçaağaç yaprağı', difficulty: 3 },
];

/**
 * Get bot words for a specific language and difficulty.
 */
export function getBotWordsForLanguage(langCode: string, difficulty?: 1 | 2 | 3): { word: string; difficulty: 1 | 2 | 3; quickDraw: string }[] {
  const lang = langCode as 'en' | 'ka' | 'ru' | 'tr';
  const entries = BOT_WORDS.filter(e => !difficulty || e.difficulty === difficulty);
  return entries.map(e => ({
    word: e[lang] || e.en,
    difficulty: e.difficulty,
    quickDraw: e.quickDraw,
  }));
}

/**
 * Get all unique Quick Draw categories used.
 */
export function getAllQuickDrawCategories(): string[] {
  return [...new Set(BOT_WORDS.map(e => e.quickDraw))];
}
