import { WordSeedData } from './seed-types';

export const trWords: WordSeedData = {
  language: {
    code: 'tr',
    name: 'Turkish',
    nativeName: 'Türkçe',
  },
  words: {
    easy: [
      'kedi', 'köpek', 'güneş', 'ağaç', 'ev',
      'araba', 'balık', 'top', 'şapka', 'ayakkabı',
      'bardak', 'yıldız', 'ay', 'elma', 'muz',
      'çiçek', 'bulut', 'yağmur', 'kitap', 'sandalye',
      'masa', 'kapı', 'pencere', 'anahtar', 'kalp',
      'saat', 'pizza', 'pasta', 'ekmek', 'yumurta',
      'süt', 'peynir', 'dondurma', 'şeker', 'kurabiye',
      'gitar', 'davul', 'piyano', 'zil', 'telefon',
      'lamba', 'otobüs', 'gemi', 'uçak', 'tren',
      'bisiklet', 'yatak', 'çorap', 'gömlek', 'pantolon',
      'eldiven', 'yüzük', 'taç', 'hayalet', 'robot',
      'uzaylı', 'yılan', 'örümcek', 'kelebek', 'domuz',
      'inek', 'at', 'tavuk', 'ördek', 'kurbağa',
      'aslan', 'ayı', 'tavşan', 'tilki', 'kurt',
      'fil', 'maymun', 'penguen', 'yunus', 'balina',
      'köpekbalığı', 'ahtapot', 'yengeç', 'kaplumbağa', 'salyangoz',
      'arı', 'karınca', 'gökkuşağı', 'dağ', 'nehir',
      'ada', 'köprü', 'kale', 'çadır', 'roket',
      'çekiç', 'kılıç', 'kalkan', 'ok', 'mum',
      'bayrak', 'kuş', 'merdiven', 'çit', 'kardan adam',
    ],
    medium: [
      'deniz feneri', 'astronot', 'denizaltı', 'yanardağ', 'şelale',
      'teleskop', 'paraşüt', 'kar tanesi', 'korkuluk', 'helikopter',
      'ambulans', 'korsan', 'dinozor', 'deniz kızı', 'tek boynuzlu at',
      'hazine', 'pusula', 'çapa', 'dürbün', 'havai fişek',
      'yel değirmeni', 'iglo', 'kasırga', 'deprem', 'tayfun',
      'karnaval', 'safari', 'orkestra', 'laboratuvar', 'iskelet',
      'vampir', 'zombi', 'kurt adam', 'kentaur', 'sfenks',
      'piramit', 'kolezyum', 'buzul', 'kanyon', 'çöl',
      'cengel', 'bataklık', 'çığ', 'tutulma', 'takımyıldız',
      'kuyruklu yıldız', 'uydu', 'portre', 'heykel', 'origami',
      'çeşme', 'avize', 'kaleydoskop', 'kum saati', 'domino',
      'dama', 'mancınık', 'trambolin', 'hamak', 'akvaryum',
      'sera', 'stetoskop', 'mikroskop', 'termometre', 'bumerang',
      'tatar yayı', 'asma köprü', 'gargoyl', 'labirent', 'kukla',
      'sarkaç', 'periskop', 'bataklık kumu', 'sapan', 'güneş saati',
      'ip cambazı', 'ağaç ev', 'daktilo', 'el arabası', 'akordiyon',
      'balerin', 'arıcı', 'demirci', 'bonsai', 'bukalemun',
      'düş kapanı', 'şömine', 'gladyatör', 'kelepçe', 'kano',
      'oduncu', 'matador', 'bülbül', 'pegasus', 'çekçekçi',
      'samuray', 'tramvay', 'büyücü', 'atölye', 'denizanası',
    ],
    hard: [
      'demokrasi', 'nostalji', 'evrim', 'yerçekimi', 'felsefe',
      'klostrofobi', 'erteleme', 'senkronizasyon', 'paradoks', 'mecaz',
      'ironi', 'alaycılık', 'hırs', 'kıskançlık', 'kaygı',
      'cesaret', 'bilgelik', 'özgürlük', 'adalet', 'ihanet',
      'bağışlama', 'kararlılık', 'savunmasızlık', 'dayanıklılık', 'huzur',
      'kaos', 'uyum', 'entropi', 'ivme', 'sabır',
      'merak', 'empati', 'devrim', 'gelenek', 'medeniyet',
      'kapitalizm', 'sosyalizm', 'göç', 'diplomasi', 'propaganda',
      'sansür', 'yolsuzluk', 'komplo', 'batıl inanç', 'yenilik',
      'algoritma', 'şifreleme', 'özyineleme', 'bant genişliği', 'enflasyon',
      'yok olma', 'fotosentez', 'manyetizma', 'elektrik', 'frekans',
      'perspektif', 'yanılsama', 'günah', 'fedakarlık', 'kurtuluş',
      'yalnızlık', 'uykusuzluk', 'déjà vu', 'aydınlanma', 'melankoli',
      'mutluluk coşkunluğu', 'histeri', 'baş dönmesi', 'kayıtsızlık', 'merhamet',
      'kibir', 'tevazu', 'minnettarlık', 'pişmanlık', 'iyimserlik',
      'kötümserlik', 'isyan', 'uyumculuk', 'ikiyüzlülük', 'dürüstlük',
      'inziva', 'sonsuzluk', 'kader', 'karma', 'vicdan',
      'ikilem', 'kalıp yargı', 'önyargı', 'hoşgörü', 'eşitlik',
      'egemenlik', 'anarşi', 'bürokrasi', 'hiyerarşi', 'özerklik',
      'biyoçeşitlilik', 'sürdürülebilirlik', 'küreselleşme', 'soylulaştırma', 'varoluşçuluk',
    ],
  },
};
