import { WordSeedData } from './seed-types';

export const enWords: WordSeedData = {
  language: {
    code: 'en',
    name: 'English',
    nativeName: 'English',
  },
  words: {
    easy: [
      'cat', 'dog', 'sun', 'tree', 'house',
      'car', 'fish', 'ball', 'hat', 'shoe',
      'cup', 'star', 'moon', 'apple', 'banana',
      'flower', 'cloud', 'rain', 'book', 'chair',
      'table', 'door', 'window', 'key', 'heart',
      'clock', 'pizza', 'cake', 'bread', 'egg',
      'milk', 'cheese', 'ice cream', 'candy', 'cookie',
      'guitar', 'drum', 'piano', 'bell', 'phone',
      'lamp', 'bus', 'boat', 'plane', 'train',
      'bike', 'bed', 'sock', 'shirt', 'pants',
      'glove', 'ring', 'crown', 'ghost', 'robot',
      'alien', 'snake', 'spider', 'butterfly', 'pig',
      'cow', 'horse', 'chicken', 'duck', 'frog',
      'lion', 'bear', 'rabbit', 'fox', 'wolf',
      'elephant', 'monkey', 'penguin', 'dolphin', 'whale',
      'shark', 'octopus', 'crab', 'turtle', 'snail',
      'bee', 'ant', 'rainbow', 'mountain', 'river',
      'island', 'bridge', 'castle', 'tent', 'rocket',
      'hammer', 'sword', 'shield', 'arrow', 'candle',
      'flag', 'kite', 'ladder', 'fence', 'snowman',
    ],
    medium: [
      'bicycle', 'lighthouse', 'astronaut', 'submarine', 'volcano',
      'waterfall', 'telescope', 'parachute', 'snowflake', 'scarecrow',
      'helicopter', 'ambulance', 'pirate', 'dinosaur', 'mermaid',
      'unicorn', 'treasure', 'compass', 'anchor', 'binoculars',
      'fireworks', 'windmill', 'igloo', 'tornado', 'earthquake',
      'hurricane', 'carnival', 'safari', 'orchestra', 'laboratory',
      'skeleton', 'vampire', 'zombie', 'werewolf', 'centaur',
      'sphinx', 'pyramid', 'colosseum', 'glacier', 'canyon',
      'desert', 'jungle', 'swamp', 'avalanche', 'eclipse',
      'constellation', 'comet', 'satellite', 'portrait', 'sculpture',
      'origami', 'fountain', 'chandelier', 'kaleidoscope', 'hourglass',
      'dominoes', 'checkers', 'catapult', 'trampoline', 'hammock',
      'aquarium', 'greenhouse', 'stethoscope', 'microscope', 'thermometer',
      'boomerang', 'crossbow', 'drawbridge', 'gargoyle', 'labyrinth',
      'marionette', 'pendulum', 'periscope', 'quicksand', 'slingshot',
      'sundial', 'tightrope', 'treehouse', 'typewriter', 'wheelbarrow',
      'zeppelin', 'accordion', 'ballerina', 'beekeeper', 'blacksmith',
      'bonsai', 'chameleon', 'dreamcatcher', 'fireplace', 'gladiator',
      'handcuffs', 'jukebox', 'kayak', 'lumberjack', 'matador',
      'nightingale', 'pegasus', 'rickshaw', 'samurai', 'trolley',
    ],
    hard: [
      'democracy', 'nostalgia', 'evolution', 'gravity', 'philosophy',
      'claustrophobia', 'procrastination', 'synchronize', 'paradox', 'metaphor',
      'irony', 'sarcasm', 'ambition', 'jealousy', 'anxiety',
      'courage', 'wisdom', 'freedom', 'justice', 'betrayal',
      'forgiveness', 'determination', 'vulnerability', 'resilience', 'serenity',
      'chaos', 'harmony', 'entropy', 'momentum', 'patience',
      'curiosity', 'empathy', 'revolution', 'tradition', 'civilization',
      'capitalism', 'socialism', 'immigration', 'diplomacy', 'propaganda',
      'censorship', 'corruption', 'conspiracy', 'superstition', 'innovation',
      'algorithm', 'encryption', 'recursion', 'bandwidth', 'inflation',
      'extinction', 'photosynthesis', 'magnetism', 'electricity', 'frequency',
      'perspective', 'illusion', 'temptation', 'sacrifice', 'redemption',
      'loneliness', 'insomnia', 'déjà vu', 'epiphany', 'melancholy',
      'euphoria', 'hysteria', 'vertigo', 'apathy', 'compassion',
      'arrogance', 'humility', 'gratitude', 'regret', 'optimism',
      'pessimism', 'rebellion', 'conformity', 'hypocrisy', 'integrity',
      'solitude', 'eternity', 'destiny', 'karma', 'conscience',
      'dilemma', 'stereotype', 'prejudice', 'tolerance', 'equality',
      'sovereignty', 'anarchy', 'bureaucracy', 'hierarchy', 'autonomy',
      'biodiversity', 'sustainability', 'globalization', 'gentrification', 'existentialism',
    ],
  },
};
